var githubHeaderTitle = "- ( ゜- ゜)つロ Github-iOS备忘  &nbsp;&nbsp;&nbsp; 2015-05-24"

function getRepoHTML(repo){
    var url;
    if (!repo || !repo.name) {
        return "";
    }

    if (repo.url && repo.url != '') {
        url = repo.url;
    } else if (repo.owner && repo.owner != ''){
        url = 'https://github.com/' + repo.owner + '/' + repo.name;
    } else {
        url = 'https://github.com/search?q=' + repo.name;
    }

    return '<tr id="' + repo.owner + '_' + repo.name + '"" repo="' + repo.name + '" owner="' + repo.owner + '">' +
    '<td><i class="icon-link"></i><a href="' + url + '" target="_blank"> ' + repo.name + '</a></td>' + 
    '<td>' + repo.desc + '</td>' + 
    '<td></td>' +
    '<td><i class="icon-star-empty"></i> </td>' +
    '<td><i class="icon-code-fork"></i> </td>' +
    '</tr>';
}

var githubList =  [
{
name:'系统基础库',
list: [

{name:'Category/Util',
list: [
    {name:'sstoolkit',          owner:'soffes',          desc:'一套Category类型的库,附带很多自定义控件 功能不错～'},
    {name:'BFKit',              owner:'FabrizioBrancati',desc:'又一套Category类型的 Kit，还有几个工具类'},
    {name:'APUtils',            owner:'andrei512',       desc:'又一套Category类型的 Kit'},
    {name:'QSKit',              owner:'quartermaster',   desc:'又一套Category类型的 Kit'},
    {name:'iOS-Categories',     owner:'shaojiankui',     desc:'又一套Category类型的 Kit'},
    {name:'BlocksKit',          owner:'zwaldowski',      desc:'将Block风格带入UIKit和Founcation'},
    {name:'cocoa-helpers',      owner:'enormego',        desc:'一些Cocoa的扩展 2年前的工程'},
    {name:'iOS-NBUKit',         owner:'CyberAgent',      desc:'一套基础工具库'},
    {name:'CoconutKit',         owner:'defagos',         desc:'一系列扩展和一些自定组件'},
    {name:'STUtils',            owner:'ldandersen',      desc:'一系列扩展包'},
    {name:'PSFoundation',       owner:'steipete',        desc:'一系列扩展 和功能增强'},
    {name:'ConciseKit',         owner:'petejkim',        desc:'一系列宏定义 挺有意思'},
    {name:'DTFoundation',       owner:'Cocoanetics',     desc:'又一系列扩展。。。'},
    {name:'BBBootstrap',        owner:'brunodecarvalho', desc:'一些常见功能的扩展库'},
    {name:'Objective-Shorthand',owner:'khanlou',         desc:'将长方法简化的Category'},
    {name:'BGUtilities',        owner:'bennyguitar',     desc:'几个简单好用的Cagegory'},
    {name:'cooliris-toolkit',   owner:'mave99a',         desc:'cooliris出品的基础工具库,从GoogleCode clone过来'},
    {name:'BaseKit',            owner:'brunow',          desc:'一套基础工具库'},
    {name:'NSObject-Utility-Categories', owner:'erica',  desc:'如题'},
    {name:'NSArray-Utilities',  owner:'erica',           desc:'如题'},
    {name:'aqtoolkit',          owner:'AlanQuatermain',  desc:'一些常用的东西'},
    {name:'DLIntrospection',    owner:'garnett',         desc:'一些NSObject的扩展'},
    {name:'YOLOKit',            owner:'mxcl',            desc:'一些方便的快速枚举方法'},
    {name:'NSDate-Extensions',  owner:'erica',           desc:'如题日期'},
    {name:'ALActionBlocks',     owner:'lavoy',           desc:'在UIControl上添加的Block事件'},
    {name:'jrswizzle',          owner:'rentzsch',        desc:'主要是swizzling'},
    {name:'moriarty',           owner:'tylerneylon',     desc:'一些还算有用的功能'},
    {name:'QSUtilities',        owner:'mikeho',          desc:'一些基础库 (Instagram有用到)'},
    {name:'libextobjc',         owner:'jspahrsummers',   desc:'一堆oc的扩展'},
    {name:'PrettyTimestamp',    owner:'jonhocking',      desc:'友好时间的扩展'},
    {name:'DateTools',          owner:'MatthewYork',     desc:'不错的时间处理相关的工具箱'},
    {name:'ios-jail-break-detector',    owner:'diwu',    desc:'检测是否越狱 有上线'},
    {name:'crackify',           owner:'itruf',           desc:'检测App是否被破解'},
    {name:'UIView-AnimatedProperty',owner:'iMartinKiss', desc:'为UIView添加动画效果的property,有用到swizzle'},
    {name:'UIView-Positioning', owner:'freak4pc',        desc:'为UIView的frame等添加更多属性，方便设置view'},
    {name:'Block-KVO',          owner:'iMartinKiss',     desc:'Block风格的KVO~'},
    {name:'MTDates',          owner:'mysterioustrousers',desc:'一些Data的category'},
    {name:'CocoaSecurity',      owner:'kelp404',         desc:'常见的哈希、加密解密算法'},
    {name:'FCFileManager',      owner:'fabiocaccamo',    desc:'更好更方便的访问文件和文件夹'},
    {name:'sskeychain',         owner:'soffes',          desc:'访问keychain 支持iOS Mac'},
    {name:'UISS',               owner:'robertwijas',     desc:'用JSON的风格设置UIKit样式'},
    {name:'Underscore.m',       owner:'robb',            desc:'仿JS的underscore.js来写的,用于访问和处理数据'},
    {name:'TICoreDataSync',     owner:'nothirst',        desc:'在不同设备间对CoreData进行同步 (iPhone iPad Mac)'},
    {name:'SoloComponents-iOS', owner:'andreyvit',       desc:'几个轻量的组件,没什么用,2年没更新'},
    {name:'MAObjCRuntime',      owner:'mikeash',         desc:'将运行时包装成ObjC'},
    {name:'Objective-C-Generics',owner:'tomersh',        desc:'通过宏定义勉强实现的范型'},
    {name:'TBMacros',           owner:'twobitlabs',      desc:'一些常用的宏定义'},
    {name:'NSString-Ruby',      owner:'zdavison',        desc:'为Ruby程序员带来的字符串相关功能'},
    {name:'ObjectiveRecord',    owner:'supermarin',      desc:'CoreData包装的活动记录 有RoR风格的API'}
]
},

{name:'基础功能',
list:[
    {name:'mediaextract',   owner:'panzi',         desc:'纯C的一些常用媒体文件的解析读取'},
    {name:'objection',      owner:'atomicobject',  desc:'一个估计是java ee写多了的人搞的。。注解依赖注入xx工厂之类的'},
    {name:'Typhoon',        owner:'typhoon-framework', desc:'IoC容器啊～～'},
    {name:'HTKit',          owner:'hoteltonight',  desc:'一票乱七八糟的东西'},
    {name:'StringScore',    owner:'thetron',       desc:'模糊匹配字符串 查找某两个字符串的相似程度'},
    {name:'RegexKitLite',   owner:'samdeane',      desc:'正则表达式库 (从SF.net mirror过来)'},
    {name:'Objective-C-RegEx-Categories',owner:'bendytree',desc:'正则表达'},
    {name:'FormatterKit',   owner:'mattt',         desc:'一个NSString的格式化工具，支持时间、颜色、地址、名字等等'},
    {name:'TransformerKit', owner:'mattt',         desc:'NSValueTransformer的封装'},
    {name:'NanoStore',      owner:'tciuro',        desc:'KV存储 (无模式/NoSQL)'},
    {name:'TMCache',        owner:'tumblr',        desc:'tumblr开源的一个内存/文件缓存，很棒'},
    {name:'PINCache',       owner:'pinterest',     desc:'pinterest开元的的一个内存/文件缓存，从TMCache修改而来，快速无死锁'},
    {name:'EGOCache',       owner:'enormego',      desc:'EGOImage里面的 Cache功能'},
    {name:'Haneke',         owner:'Haneke',        desc:'一个开箱即用的图片Cache'},
    {name:'HJCache',        owner:'markofjohnson', desc:'一个缓存网络内容等的Cache'},
    {name:'RNCryptor',      owner:'RNCryptor',     desc:'加密解密相关 貌似更上流, note:去看一下他博客,有更详细的文章'},
    {name:'MIHCrypto',      owner:'hohl',          desc:'各种加密解密算法 (AES/DES/RSA/MD5/SHA等)，包装自OpenSSL'},
    {name:'INBSecurityCrypto', owner:'Daniate',    desc:'一些加密解密工具和示例'},
    {name:'ssziparchive',   owner:'soffes',        desc:'zip压缩 zip解压~'},
    {name:'ZipKit',         owner:'kolpanic',      desc:'一个ZipKit 从bitbucket Mirror过来'},
    {name:'ZipKit',    owner:'FivesquareSoftware', desc:'如同ZipKit 改为ARC了'},
    {name:'zipzap',         owner:'pixelglow',     desc:'Zip文件处理 底层为libz'},
    {name:'MTMigration',owner:'mysterioustrousers',desc:'版本升时执行一次'},
    {name:'MTControl',  owner:'mysterioustrousers',desc:'jQuery风格touch事件绑定'},
    {name:'storage',        owner:'thisandagain',  desc:'快速、线程安全的I/O存储操作'},
    {name:'CHCSVParser',    owner:'davedelong',    desc:'CVS文件解析'},
    {name:'YLMoment',       owner:'YannickL',      desc:'日期的解析，格式化等，支持多语言'},
    {name:'CMUnistrokeGestureRecognizer',owner:'chrismiles',desc:'各种奇怪的手势检测'},
    {name:'EKAlgorithms',owner:'EvgenyKarkan', desc:'常见算法的ObjC实现，包括排序、查找、数组、字符串、常用数据结构..'}
]
},

{name:'框架/封装',
list:[
    {name:'three20',            owner:'facebookarchive',   desc:'Facebook 的一个曾经用得广泛的庞大的iOS开发框架 陈旧并且已不再维护'},
    {name:'nimbus',             owner:'jverkoey',          desc:'three20替代品 又一个庞大的框架'},
    {name:'BeeFramework',       owner:'gavinkwoe',         desc:'一个基于MVC的框架, 比较大..'},
    {name:'OmniGroup',          owner:'omnigroup',         desc:'一套很庞大的库(OmniGroup) 支持Mac和iOS'},
    {name:'ReactiveCocoa',      owner:'ReactiveCocoa',     desc:'一套响应式编程的框架(Functional Reactive Programming) 支持Mac'},
    {name:'componentkit',       owner:'facebook',          desc:'Facebook 的一个功能性的、响应式UI框架, 被应用于Facebook App'},
    {name:'AsyncDisplayKit',    owner:'facebook',          desc:'Facebook 出的一个用于保持UI流畅性的框架, 其原理被用于Paper'},
    {name:'react-native',       owner:'facebook',          desc:'Facebook 出的框架, 通过JS和React构建原生界面'},
    {name:'KVOController',      owner:'facebook',          desc:'Facebook 出的线程安全KVO'},
    {name:'MAKVONotificationCenter',owner:'mikeash',       desc:'一个自定义KVO Center'},
    {name:'WebViewJavascriptBridge', owner:'marcuswestin', desc:'UIWebView和Cocoa之间的事件传递'},
    {name:'JavaScriptBridge',   owner:'kishikawakatsumi',  desc:'JavaScriptCore到Cocoa之间的变量传递和代码执行Bridge'},
    {name:'OCUDL',              owner:'dbachrach',         desc:'自定义literals 有点意思～～'},
    {name:'Motif',              owner:'erichoracek',       desc:'通过 JSON 定制界面，支持 Live Reload'},
    {name:'Kiwi',               owner:'kiwi-bdd',          desc:'BDD for iOS'},
    {name:'MagicalRecord',      owner:'magicalpanda',      desc:'CoreData的包装 简化代码'},
    {name:'fmdb',               owner:'ccgus',             desc:'SQLite的封装'},
    {name:'KZPropertyMapper',   owner:'krzysztofzablocki', desc:'一个Model的封装,类JSON'},
    {name:'BlockInjection',     owner:'tokorom',           desc:'为某个方法前后注入Block，类似AOP'},
    {name:'Aspects',            owner:'steipete',          desc:'又一个AOP库，用swizzle实现的切面...'},
    {name:'Bolts-iOS',          owner:'BoltsFramework',    desc:'低层次的，更好的管理异步任务的库，支持Facebook AppLinks(同时有Android版)'},
    {name:'NSObject-ObjectMap', owner:'uacaps',            desc:'JSON和XML包装到Object'},
    {name:'Ejecta',             owner:'phoboslab',         desc:'通过OpenGL OpenAL来实现 WebCanvas JS等,很庞大~'},
    {name:'FCModel',            owner:'marcoarment',       desc:'为SQL程序员包装一下CoreData'}
]
},

{name:'功能/封装',
list:[
    {name:'iOS-System-Services',owner:'Shmoopi',      desc:'获取各种设备信息 包括硬件、网络、内存、进程等等'},
    {name:'iAppInfos',       owner:'leverdeterre',    desc:'简单获取设备信息，例如设备、空间、Provisionning'},
    {name:'LocationManager', owner:'intuit',          desc:'更好用的获取和追踪设备位置的工具，包括GPS信息'},
    {name:'MKStoreKit',      owner:'MugunthKumar',    desc:'iAP用的库'},
    {name:'CargoBay',        owner:'mattt',           desc:'一个包装iAP StoreKit的库'},
    {name:'RMStore',         owner:'robotmedia',      desc:'很轻量的iAP包装'},
    {name:'OpenUDID',        owner:'ylechelle',       desc:'系统UDID替代方案'},
    {name:'UIDevice-with-UniqueIdentifier-for-iOS-5',owner:'gekitz', desc:'另一个UUID解决方案 但iOS7不能用了'},
    {name:'uidevice-extension', owner:'erica',        desc:'一系列UIDevice的扩展 有PrivateAPI 最新的工程在cookbook-code里'},
    {name:'InAppSettingsKit', owner:'futuretap',      desc:'包装了设置、URLScheme、Mail、Icon等东西'},
    {name:'DTWebArchive',     owner:'Cocoanetics',    desc:'允许访问剪贴板中的WebArchive格式富文本'},
    {name:'routable-ios',     owner:'clayallsopp',    desc:'inApp的URL定义 在App内打开自定义URL (解耦)'},
    {name:'JLRoutes',         owner:'joeldev',        desc:'复杂的URL Scheme解析和路由'},
    {name:'Emoji',            owner:'limejelly',      desc:'访问Emoji图片的功能'},
    {name:'PDKeychainBindingsController', owner:'carlbrown', desc:'以类似UserDefault的方式访问Keychain'},
    {name:'CoreTextWrapper',  owner:'akosma',         desc:'一个CoreText库的包装'},
    {name:'Slash',            owner:'chrisdevereux',  desc:'对AttributeString的封装'},
    {name:'ABContactHelper',  owner:'erica',          desc:'访问联系人'},
    {name:'APAddressBook',    owner:'Alterplay',      desc:'封装了访问通信录/联系人的功能'},
    {name:'GVUserDefaults',   owner:'gangverk',       desc:'包装了 NSUserDefaults，只需要声明属性就能用，很方便'},
    {name:'YapDatabase',      owner:'yapstudios',     desc:'一个KV库，包装自sqlite，但有更多包装好的功能，比如缓存/全文搜索'},
    {name:'YTKKeyValueStore', owner:'yuantiku',       desc:'又一个KV库，简单包装自sqlite(FMDB)'},
    {name:'realm-cocoa',      owner:'realm',          desc:'为移动设备专门设计的数据库，旨在替代sqlite/CoreData'},
    {name:'iHasApp',          owner:'danielamitay',   desc:'检测某个App是否安装，集成了常见的URL Scheme'},
    {name:'UIActivityCollection',owner:'shu223',      desc:'Github上UIActivity项目的集合'},
    {name:'STPTransitions',   owner:'stepanhruda',    desc:'更好的 自定义ViewCtrl 过渡动画API'},
    {name:'PureLayout',       owner:'smileyborg',     desc:'AutoLayout的封装，支持iOS/Mac，支持swift'},
    {name:'Masonry',          owner:'cloudkite',      desc:'AutoLayout的封装'},
    {name:'KeepLayout',       owner:'iMartinKiss',    desc:'AutoLayout的封装 貌似比较好用'},
    {name:'JTSHardwareInfo',  owner:'jaredsinclair',  desc:'定义enum来获取和判断设备型号'},
    {name:'MTGeometry',       owner:'mysterioustrousers',desc:'CGPoint/Size/Rect的一些几何学的计算'},
    {name:'MYSRuntime',       owner:'mysterioustrousers',desc:'包装了RunTime的一些方法，使用更容易'},
    {name:'MTStringAttributes',owner:'mysterioustrousers',desc:'更容易的访问和修改 NSAttributedString'},
    {name:'MTPDF',            owner:'mysterioustrousers',desc:'基于CF的PDF Object封装，更容易的访问和创建PDF'}
    
]
},

]
},

{name:'网络',
list:
[

{name:'基础',
list:[
    {name:'AFNetworking',       owner:'AFNetworking', desc:'很棒的HTTP网络通信库'},
    {name:'asi-http-request',   owner:'pokeb',        desc:'一个HTTP库 同样很知名 性能好,稳定 但已不再维护'},
    {name:'MKNetworkKit',       owner:'MugunthKumar', desc:'一个HTTP库 支持Mac 同样也不错'},
    {name:'STHTTPRequest',      owner:'nst',          desc:'一个非常简单的http库,包装了NSURLConnection'},
    {name:'SVHTTPRequest',      owner:'TransitApp',   desc:'一个很简洁的http库'},
    {name:'RestKit',            owner:'RestKit',      desc:'一个HTTP库 用来与RESTful的服务进行交互'},
    {name:'AFIncrementalStore', owner:'AFNetworking', desc:'用CoreData和AFNetworking 将HTTP数据持久化'},
    {name:'CocoaAsyncSocket',   owner:'robbiehanson', desc:'TCP/UDP包装库 支持Mac 很棒'},
    {name:'Reachability',       owner:'tonymillion',  desc:'判断设备网络情况 和苹果的很像 用ARC、GCD'},
    {name:'SDReachability',     owner:'rs',           desc:'判断设备网络情况 和苹果的很像，更友好？'},
    {name:'socket.IO-objc',     owner:'pkyeck',       desc:'支持HTTP 长轮询 socket.io'},
    {name:'DTBonjour',          owner:'Cocoanetics',  desc:'Bonjour和Wifi'},
    {name:'XMPPFramework',      owner:'robbiehanson', desc:'XMPP客户端的库～ 支持Mac'},
    {name:'CocoaHTTPServer',    owner:'robbiehanson', desc:'一个轻量 HTTP Server 支持Mac'},
    {name:'GCDWebServer',       owner:'swisspol',     desc:'一个轻量 HTTP Server 用GCD实现的事件驱动'},
    {name:'HTTPKit',            owner:'fjolnir',      desc:'一个轻量/高性能的嵌入式 HTTP Web Server,功能完整强大,基于Mongoose,可以用来写服务~'},
    {name:'Barista',            owner:'stevestreza',  desc:'一个 HTTP Web Server，可以用来写服务'},
    {name:'mongoose',           owner:'cesanta',      desc:'纯C的HTTP Web服务器lib,嵌入式/跨平台'},
    {name:'fossa',              owner:'cesanta',      desc:'纯C的多协议服务器lib,嵌入式/跨平台,支持HTTP,Websocket,MQTT,mDNS等协议'},
    {name:'SocketRocket',       owner:'square',       desc:'WebSocket客户端～'},
    {name:'MailCore',           owner:'MailCore',     desc:'IMAP SMTP邮件协议'},
    {name:'CocoaSPDY',          owner:'twitter',      desc:'SPDY协议~'},
    {name:'Interpreter',        owner:'node-app',     desc:'Node.js for iOS 7, 已不再维护'}
]
},

{name:'JSON',
list:[
    {name:'JSONKit',         owner:'johnezang',  desc:'性能非常好的JSON解析库, 但目前已经可以用系统API替代了'},
    {name:'json-framework',  owner:'stig',       desc:'SBJson 曾经用得很广泛的JSON 性能差'},
    {name:'TouchJSON',       owner:'TouchCode',  desc:'又一个JSON库'},
    {name:'yajl-objc',       owner:'gabriel',    desc:'一个JSON库 可以支持流解析 支持Mac'},
    {name:'Mantle',          owner:'Mantle',     desc:'JSON解析与对象映射的库,Github自家出的,可靠且功能强大'},
    {name:'JSONModel',       owner:'icanzilb',   desc:'JSON解析与对象映射的库,应用广泛'},
    {name:'MJExtension',     owner:'CoderMJLee', desc:'JSON解析与对象映射的库'}
]
},

{name:'XML/Html',
list:[
    {name:'MWFeedParser',    owner:'mwaterfall',   desc:'Feed/Atom解析'},
    {name:'RSSKit',          owner:'H2CO3',        desc:'RSS Atom解析'},
    {name:'ElementParser',   owner:'Objective3',   desc:'提供Html和XML的解析'},
    {name:'hpple',           owner:'topfunky',     desc:'提供Html/XML解析'},
    {name:'Ono',             owner:'mattt',        desc:'Ono (斧), Html/XML解析,包装自libxml2'},
    {name:'Objective-C-HMTL-Parser',owner:'zootreeves',desc:'一个简单好用的HTML解析 包装了下libxml'},
    {name:'OCGumbo',         owner:'tracy-e',      desc:'一个OC版HTML解析库， 包装自Google Gumbo(C99)'},
    {name:'RaptureXML',      owner:'ZaBlanc',      desc:'一个简单的XML解析器 包装了libxml'},
    {name:'KissXML',         owner:'robbiehanson', desc:'解析XML的库 包装了libxml'},
    {name:'TBXML',           owner:'71squared',    desc:'快速解析xml的库'},
    {name:'xmldocument',     owner:'nfarina',      desc:'又一个解析XML的库'},
    {name:'XMLDictionary',   owner:'nicklockwood', desc:'蛮好用的一个XML转NSDictionary的类~'},
    {name:'XML-to-NSDictionary',owner:'bcaccinolo',desc:'XML转NSDictionary'},
    {name:'MMMarkdown',      owner:'mdiep',        desc:'一个渲染Markdown到HTML的小引擎'},
    {name:'Ashton',          owner:'IdeasOnCanvas',desc:'在NSAttrbuteString和Html之间转换'},
    {name:'XMLParser',       owner:'Zedenem',      desc:'XML解析成json～'}
    ]
},
{name:'功能性',
list:[
    {name:'SDWebImage',       owner:'rs',            desc:'网络图片&缓存,很棒,很多App都在用'},
    {name:'FastImageCache',   owner:'path',          desc:'网络图片&缓存,Path开发'},
    {name:'EGOImageLoading',  owner:'enormego',      desc:'下载使用网络图片的库'},
    {name:'AsyncImageView',   owner:'nicklockwood',  desc:'异步加载和显示图片'},
    {name:'TCBlobDownload',   owner:'thibaultCha',   desc:'下载大文件/ 断点续传'},
    {name:'GroundControl',    owner:'mattt',         desc:'一个通过远程plist改变配置的库'},
    {name:'appirater',        owner:'arashpayan',    desc:'提醒用户稍后到AppStore给你评分的功能'},
    {name:'iRate',            owner:'nicklockwood',  desc:'类似appirater 提醒用户稍后到AppStore评分 支持Mac'},
    {name:'ShareKit',         owner:'ShareKit',      desc:'分享到国外的一些社交网站 的功能 用的的人挺多'},
    {name:'Harpy',            owner:'ArtSabintsev',  desc:'新版本更新提醒, 使用时需留意AppStore审核'},
    {name:'iVersion',         owner:'nicklockwood',  desc:'新版本更新提醒 功能提示'},
    {name:'DataKit',          owner:'eaigner',       desc:'以类似CoreData的Model 来获取网络资源'},
    {name:'SDURLCache',       owner:'rs',            desc:'URL缓存'},
    {name:'objective-git',    owner:'libgit2',       desc:'libgit的包装 挺庞大'},
    {name:'nsrails',          owner:'dingbat',       desc:'RoR风格的网络交互API'}
    ]
},
{name:'SDK',
list:[
    {name:'CZWeatherKit',         owner:'comyarzaheri',   desc:'获取天气数据,支持多个天气服务'},
    {name:'openshare',            owner:'100apps',        desc:'国内几个社交网络的分享功能，直接调API，代码精简'},
    {name:'facebook-ios-sdk',     owner:'facebook',       desc:'Facebook的SDK'},
    {name:'MGTwitterEngine',      owner:'mattgemmell',    desc:'一套Twtter库'},
    {name:'Twitter-OAuth-iPhone', owner:'bengottlieb',    desc:'Twitter的OAuth功能'},
    {name:'Foursquare-API-v2',    owner:'Constantine-Fry',desc:'Foursquare的库'},
    {name:'objectiveflickr',      owner:'lukhnos',        desc:'Flicker API'},
    {name:'octokit.objc',         owner:'octokit',        desc:'Github的API'},
    {name:'ParcelKit',            owner:'overcommitted',  desc:'Dropbox封装CoreData'},
    {name:'cocoalibspotify',      owner:'spotify',        desc:'spotify官方SDK'},
    {name:'DeepBeliefSDK',        owner:'jetpacapp',      desc:'Jetpac 图片识别的SDK'},
    {name:'GDFileManagerKit',     owner:'GrahamDennis',   desc:'访问 dropbox GDrive之类的云存储'}
    ]
},

]
},


{name:'音频',
list:[
    {name:'AudioKit',            owner:'audiokit',     desc:'强大的iOS音频工具箱,支持音频分析、处理、合成、音序器'},
    {name:'EZAudio',             owner:'syedhali',     desc:'iOS音频库，支持录音、回放、波形图显示等，效果不错'},
    {name:'TheAmazingAudioEngine', owner:'TheAmazingAudioEngine', desc:'一个声音库 包装了CoreAudio'},
    {name:'AudioStreamer',       owner:'mattgallagher',desc:'音频流播放库 支持Mac'},
    {name:'SimpleAudioEngine',   owner:'akinLiu',      desc:'一个简单的播放声音的库'},
    {name:'DOUAudioStreamer',    owner:'douban',       desc:'豆瓣的音频流播放'},
    {name:'StreamingKit',        owner:'tumtumtum',    desc:'流音频播放，功能丰富'},
    {name:'iOSSystemSoundsLibrary',owner:'TUNER88',    desc:'列出和播放iOS系统声音~'},
    {name:'novocaine',           owner:'alexbw',       desc:'一个声音库 录音放音 页面上有CoreAudio的教程链接'},
    {name:'audiograph',          owner:'tkzic',        desc:'一个AU的教程 & 示例工程~'},
    {name:'MIDIFileSequence',    owner:'genedelisa',   desc:'基于AU的，解析Midi序列和播放的库'},
    {name:'NVDSP',               owner:'bartolsthoorn',desc:'一个iOS上的DSP处理'},
    {name:'Blip-Synth',          owner:'lucaas',       desc:'一个Blip声音合成器'},
    {name:'PGMidi',              owner:'petegoodliffe',desc:'一个Midi库'},
    {name:'sc_listener',         owner:'stephencelis', desc:'检测系统声音等级的库'},
    {name:'ObjectAL-for-iPhone', owner:'kstenerud',    desc:'一个OpenAL的包装库 比较好用'},
    {name:'SoundBankPlayer',     owner:'hollance',     desc:'一个仿SoundFout的库 但更简单'},
    {name:'Finch',               owner:'zoul',         desc:'对底层的OpenAL包装'},
    {name:'SoundManager',        owner:'nicklockwood', desc:'很简单的Sound播放管理'},
    {name:'OrigamiEngine',       owner:'ap4y',         desc:'音乐播放引擎 支持 flac, cue, mp3, m4a, m3u'},
    {name:'libpd',               owner:'libpd',        desc:'一个用PD来创造音乐的库？ 纯C'},
    {name:'pd-for-ios',          owner:'libpd',        desc:'同libpd'},
    {name:'RCTMidiLib',          owner:'recotana',     desc:'一个Pad连接Midi设备通信的包装'},
    {name:'octave',              owner:'scopegate',    desc:'一个免费的音效库 包括48个UI音效'},
    {name:'RBDMuteSwitch',       owner:'Rich2k',       desc:'在iOS5上检测是否静音'},
    {name:'sfArkLib',            owner:'raboof',       desc:'转换sfArk和sf2的库 很简单'},
    {name:'sfarkxtc',            owner:'raboof',       desc:'简单解压sfArk的一个cpp'},
    {name:'unsfark',             owner:'raboof',       desc:'和上面sfArkXTm一样，是老一点的纯C版本'},
    {name:'MuseScore',           owner:'musescore',    desc:'一个跨平台的音乐软件～ not iOS'},
    {name:'OpenSFZ',             owner:'WhiteNoise',   desc:'一个SF2的处理库(Github上有详细说明) An Open SFZ player & SF2 based on SFZero'},
    {name:'alsaplayer',          owner:'alsaplayer',   desc:'一个Linux下PCM库 有sf2 midi等处理过程'}
    ]
},


{name:'游戏',
list:[
    {name:'cocos2d-iphone',               owner:'cocos2d', desc:'2D游戏引擎 (SpriteKit后来居上了..)'},
    {name:'cocos2d-iphone-extensions',    owner:'cocos2d', desc:'cocos2d的扩展'},
    {name:'smooth-drawing',     owner:'krzysztofzablocki', desc:'cocos2d中画出平滑的曲线'},
    {name:'tiny-wings',                   owner:'haqu',    desc:'仿TinyWings的Demo 用Cocos2D'},
    {name:'Tiny-Wings-Remake-on-Android', owner:'diwu',    desc:'如题.'},
    {name:'tweejump',               owner:'haqu',          desc:'是小鸟就跳100层 Game'},
    {name:'wizardwar',              owner:'seanhess',      desc:'一个很完整的2D小游戏,支持对战,已在AppStore上架'},
    {name:'Sparrow-Framework',      owner:'PrimaryFeather',desc:'开源游戏引擎 2D 1.0版'},
    {name:'Sparrow-Framework',      owner:'Gamua',         desc:'开源游戏引擎 2D 2.0版'},
    ]
},



{name:'图像',
list:[

{name:'视频/OpenGL',
list:[
    {name:'ijkplayer',         owner:'Bilibili',        desc:'B站出的视频播放器库,基于ffmpeg,支持iOS/Android,支持流播放'},
    {name:'kxmovie',           owner:'kolyvan',         desc:'一个基于ffmpeg的视频播放器'},
    {name:'KRVideoPlayer',     owner:'36Kr-Mobile',     desc:'类似Weico的播放器，支持竖屏模式下全屏播放'},
    {name:'GPUImage',          owner:'BradLarson',      desc:'基于GPU的实时图像视频处理 '},
    {name:'XBImageFilters',    owner:'xissburg',        desc:'一个GPU实时处理的库 类似GPUImage'},
    {name:'FilterKit',         owner:'eklipse2k8',      desc:'在iOS中构建和调节滤镜的库，基于GPUImage'},
    {name:'videoshader',       owner:'snakajima',       desc:'视频滤镜库，支持用脚本调节效果，功能丰富'},
    {name:'CeedGL',            owner:'creaceed',        desc:'一个OpenGL的包装 用起来更方便'},
    {name:'rend-ios',          owner:'antonholmquist',  desc:'一个OpenGL的轻量包装 接近UIKit'},
    {name:'GLView',            owner:'nicklockwood',    desc:'在UIView的包装 方便使用OpenGL'},
    {name:'sift-gpu-iphone',   owner:'Moodstocks',      desc:'一个包装GL用的,不知道干毛的'},
    {name:'ShaderManager',     owner:'TwoLivesLeft',    desc:'如题 一个Manager 管理创建Shader'},
    {name:'GLImageProcessing', owner:'twenty3',         desc:'演示如何用GPU处理图片'},
    {name:'FRD3DBarChart',     owner:'sebastienwindal', desc:'用OpenGL绘制的3D柱形图'},
    {name:'EarthView',         owner:'RossAnderson',    desc:'显示3D地形图 用OpenGL'},
    {name:'CoreAR',            owner:'sonsongithub',    desc:'一个挺有意思的AR'},
    {name:'VRToolKit',         owner:'benlodotcom',     desc:'一个虚拟现实的库'},
    {name:'kickflip-ios-sdk',  owner:'Kickflip',        desc:'视频采集和直播'},
    {name:'LayerSprites',      owner:'nicklockwood',    desc:'加载精灵图 (Sprite)'}
    ]
},
{name:'图像显示/解析',
list:[
    {name:'Concorde',       owner:'contentful-labs',desc:'利用libjpeg-turbo来更快速地解析JPEG,并支持边下载边解析&显示'},
    {name:'FLAnimatedImage',        owner:'Flipboard',    desc:'GIF的显示，低内存，性能/效果好, 方便调试'},
    {name:'UIImageView-PlayGIF',    owner:'yfme',         desc:'GIF的显示，高性能低内存，接口好用'},
    {name:'OLImageView',            owner:'ondalabs',     desc:'GIF的显示，不错'},
    {name:'YLGIFImage',             owner:'liyong03',     desc:'GIF的显示，也不错'},
    {name:'VVeboImageView',               owner:'johnil', desc:'以较低内存显示gif，效果一般'},
    {name:'uiimage-from-animated-gif',    owner:'mayoff', desc:'显示gif，使用简单、耗内存'},
    {name:'AnimatedGIFImageSerialization',owner:'mattt',  desc:'gif的序列化、UIImage的支持'},
    {name:'WebPImageSerialization',       owner:'mattt',  desc:'webp的序列化、UIImage的支持'},
    {name:'UIFontSerialization',          owner:'mattt',  desc:'字体文件的序列化、UIFont的支持'},
    {name:'DFImageManager', owner:'kean',          desc:'图片下载、缓存、处理、显示一揽子'},
    {name:'PocketSVG',      owner:'arielelkin',    desc:'svg图像解析和显示，小巧好用'},
    {name:'fmpsd',          owner:'ccgus',         desc:'psd图像读写 (从Acorn抠出来的逻辑)'},
    {name:'SFPSDWriter',    owner:'shinyfrog',     desc:'psd图层操作/写入'},
    {name:'MMLayershots',   owner:'vpdn',          desc:'截屏并写入为psd文件'}
    ]
},
{name:'图像处理',
list:[
    {name:'NYXImagesKit',        owner:'Nyx0uf',       desc:'一套图像处理的库 加在UIImage上'},
    {name:'ios-image-filters',   owner:'esilverberg',  desc:'UIImage扩展 类似PS的功能 用CoreImage'},
    {name:'vImageCategory',      owner:'shu223',       desc:'UIImage扩展 简单的一些处理'},
    {name:'MGImageUtilities',    owner:'mattgemmell',  desc:'几个简单的图片处理 UIImage'},
    {name:'UIImageAdjust',       owner:'coryleach',    desc:'一些UIImage的扩展 如亮度 模糊等'},
    {name:'CKImageAdditions',    owner:'cmkilger',     desc:'一些UIImage的不错功能～'},
    {name:'UIImage-BlurredFrame',owner:'Adrian2112',   desc:'仅模糊图片中的一块区域～'},
    {name:'LBBlurredImage',      owner:'lukabernardi', desc:'UIImage扩展 可以模糊 不知道性能如何'},
    {name:'FFAngularPointilism', owner:'FindForm',     desc:'三角马赛克效果，支持动画'},
    {name:'TCam',                owner:'azamsharp',    desc:'用CIFIlter实现的类似Instagram的类'},
    {name:'CLImageEditor',       owner:'yackle',       desc:'一个功能齐全的图像处理(滤镜/曲线/裁减/旋转/等等~)'},
    {name:'PKCoreTechniques',    owner:'pkluz',        desc:'CA和CG的特性演示'},
    {name:'UIImage-Categories',  owner:'mbcharbonneau',desc:'UIImage的一些扩展'},
    {name:'uiimage-dsp',         owner:'gdawg',        desc:'UIImage模糊的一些方法'},
    {name:'iOS7-Trans-Blur',     owner:'NickTitle',    desc:'将图片中某块形状的区域变模糊'},
    {name:'UIImage-Sprite-Additions', owner:'r3econ',  desc:'UIImage取Sprite~'},
    {name:'iOS-Scratch-n-See',   owner:'moqod',        desc:'类似结冰玻璃用手画开的效果~'},
    {name:'OBGradientView',      owner:'ole',          desc:'一个渐变色的CALayer 比系统的好用些'},
    {name:'ANImageBitmapRep',    owner:'unixpickle',   desc:'一些Bitmap处理的方法'},
    {name:'KGNoise',             owner:'kgn',          desc:'产生带噪音的Image 支持Mac'},
    {name:'KGNoiseColorTester',  owner:'EricEllett',   desc:'上面KGNoise的演示'},
    {name:'SQRiskCursor',        owner:'nst',          desc:'一个用CA和UIControl自定义控件的例子'},
    {name:'AmazeKit',            owner:'detroit-labs', desc:'据说是为PNG加速 或自己画 主要为控件提升性能的'},
    {name:'UIImage-PDF',         owner:'mindbrix',     desc:'如题 用UIImage来显示PDF'},
    {name:'JMNoise',           owner:'jasonmorrissey', desc:'给UIView添加Noise噪音的'},
    {name:'SWSnapshotStackView', owner:'snwau',        desc:'图片加上Stack外框'},
    {name:'RMShapedImageView',   owner:'robotmedia',   desc:'一个UIImageView的子类 能忽略透明地方的点击'},
    {name:'MOOMaskedIconView',   owner:'peyton',       desc:'一个通过Mask显示Icon的库 只要一个Mask 可以生成很多风格的Icon 类似Tabbar'},
    {name:'FTAssetRenderer',     owner:'Fingertips',   desc:'运行时的图像Mask生成?'},
    {name:'wolfpack',            owner:'justin',       desc:'图像处理库CI CG'},
    {name:'DSGraphicsKit',  owner:'Discontinuity-srl', desc:'支持图片常见处理 视图控制3D等'},
    {name:'UIImage-Helpers',     owner:'NZN',          desc:'几个Category小功能：截图、模糊、纯色'},
    {name:'cam',                 owner:'thisandagain', desc:'一个AVFoundation的封装、照相等功能'},
    {name:'Filtrr',              owner:'OmidH',        desc:'几个Filter 速度也不行'},
    {name:'PhotoTweaks',         owner:'itouch2',      desc:'一个图片调整的控件，支持旋转和裁剪'},
    {name:'UIImageView_FaceAwareFill', owner:'Julioacarrettoni', desc:'用CoreImage人脸识别，自动调整图片位置，让人脸居中'},
    {name:'ZXingObjC',           owner:'TheLevelUp',   desc:'ZXing 二维码/条形码处理'},
    {name:'RSBarcodes',          owner:'yeahdongcn',   desc:'二维码/条形码识别/合成'},
    {name:'Tesseract-OCR-iOS',   owner:'gali8',        desc:'OCR文字识别'},
    {name:'card.io-iOS-source',  owner:'card-io',      desc:'快速强大的信用卡识别库，被Uber/PayPal等公司使用'},
    {name:'ANPR',                owner:'chroman',      desc:'车牌识别,基于OpenCV'}
    ]
},
{name:'颜色',
list:[
    {name:'uicolor-utilities',    owner:'kballard',     desc:'UIColor扩展和色板'},
    {name:'color',                owner:'thisandagain', desc:'一系列UIColor扩展'},
    {name:'ColorUtils',           owner:'nicklockwood', desc:'一个UIColor扩展'},
    {name:'ColorConverter',       owner:'alessani',     desc:'RGB和HSL转换'},
    {name:'InfColorPicker',       owner:'InfinitApps',  desc:'一个色彩选择器'},
    {name:'RSColorPicker',        owner:'RSully',       desc:'一个不错的色彩选择器 有放大镜'},
    {name:'colorpicker',          owner:'kartech',      desc:'一个很强大的ColorPicker 包装了挺多东西'},
    {name:'ColorPicker',          owner:'Thallius',     desc:'功能很棒的一个取色'},
    {name:'ILColorPicker',        owner:'jawngee',      desc:'一个还算标准的ColorPicker'},
    {name:'NPColorPicker',        owner:'neopixl',      desc:'一个HSV三角取色器'},
    {name:'KZColorPicker',        owner:'alexrestrepo', desc:'又一个HSV圆盘取色器'},
    {name:'Color-Picker-for-iOS', owner:'hayashi311',   desc:'一个简单的单色Picker 有一个滑块'},
    {name:'LEColorPicker',        owner:'luisespinoza', desc:'一个ColorPicker可以取到图片的主色调等'},
    {name:'UIColor-converter',    owner:'charlymr',     desc:'一些UIColor的工具～～'},
    {name:'SUColor',              owner:'sumihiro',     desc:'提供2K多的日本色'},
    {name:'Colours',              owner:'bennyguitar',  desc:'提供不少常用色 和几个方法'},
    {name:'ColorArt',             owner:'panicinc',     desc:'类似iTunes的 取一幅图画的主要背景颜色等 (这是个Mac功能)'},
    {name:'SOZOChromoplast',      owner:'sozorogami',   desc:'提取图片特征色'},
    {name:'DominantColor',        owner:'indragiek',    desc:'提取图片特征色 (基于Lab色彩空间和 k-means 聚类算法)'},
    {name:'iOS7Colors',           owner:'claaslange',   desc:'iOS7的几种常用颜色'}
    ]
},

{name:'绘图库',
list:[
    {name:'iOSPlot',                   owner:'honcheng',       desc:'画饼图/折线图的库 用CA'},
    {name:'PNChart',                   owner:'kevinzhow',      desc:'扁平风格的折线图/柱形图'},
    {name:'TEAChart',                  owner:'xhacker',        desc:'扁平风格的饼图/柱形图'},
    {name:'ios-linechart',             owner:'mruegenberg',    desc:'简单好用的饼图/折线图'},
    {name:'JBChartView',               owner:'Jawbone',        desc:'简单的 有动画的折线图/柱形图 iOS7 only'},
    {name:'JYRadarChart',              owner:'johnnywjy',      desc:'雷达图(螂蛛网图), 风格多样'},
    {name:'BEMSimpleLineGraph',        owner:'Boris-Em',       desc:'曲线图'},
    {name:'Core-Animation-Pie-Chart',  owner:'briancoyner',    desc:'用CA画饼图 示例'},
    {name:'MSSimpleGauge',             owner:'sabymike',       desc:'扇形仪表盘'},
    {name:'FBDigitalFont',             owner:'lyokato',        desc:'LED液晶效果荧光字体，用CG实现'},
    {name:'FBGlowLabel',               owner:'lyokato',        desc:'LED液晶效果荧光字体，UILabel'},
    {name:'ADGraphView',               owner:'Antondomashnev', desc:'一个CG绘画库 股票曲线演示'},
    {name:'SVGKit',                    owner:'SVGKit',         desc:'一个用CA来呈现SVG图片的库'},
    {name:'Smooth-Line-View',          owner:'levinunnink',    desc:'用QuartZ画出平滑的曲线'},
    {name:'Smooth-Line-View',          owner:'yusenhan',       desc:'用上面的库搭建的比较完整的画板功能 有取色器等'},
    {name:'PPSSignatureView',          owner:'jharwig',        desc:'一个QuartZ 触摸绘制平滑曲线～～～'},
    {name:'DynamicGraphView',          owner:'freshking',      desc:'动态折线图'},
    {name:'XYPieChart',                owner:'xyfeng',         desc:'饼图~有动画'},
    {name:'BEMSimpleLineGraph',        owner:'Boris-Em',       desc:'折线图，有动画，功能一般'},
    {name:'Animated-Paths',            owner:'ole',            desc:'动画画出文字和图形的轮廓~'}
    ]
},

]
},

{name:'动画/效果',
list:[

{name:'CA',
list:[
    {name:'Shapes',                   owner:'DenHeadless',  desc:'基于CASharpLayer实现的关键帧补间动画，比较方便'},
    {name:'CA360',                    owner:'neror',        desc:'一套完整的CA动画Demo'},
    {name:'Core-Animation-Fun-House', owner:'briancoyner',  desc:'一套CA动画展示Demo'},
    {name:'Core-Animation-Demos',     owner:'tapharmonic',  desc:'一套CA动画Demo'},
    {name:'EnterTheMatrix',           owner:'mpospese',     desc:'CA动画演示Demo'},
    {name:'ftutils',                  owner:'neror',        desc:'一套CA的Util库 有一些常用动画'},
    {name:'Dazzle',                   owner:'lichtschlag',  desc:'用CA实现的各种有趣的粒子效果'},
    {name:'AGGeometryKit',            owner:'hfossli',      desc:'CA和3D效果等'},
    {name:'RBBAnimation',             owner:'robb',         desc:'基于block的CA动画'},
    {name:'JHChainableAnimations',    owner:'jhurray',      desc:'通过链式代码让动画实现得更轻松'}
    ]
},
{name:'动画曲线',
list:[
    {name:'pop',                         owner:'facebook',   desc:'Facebook Paper的动画库，支持弹簧动画，支持实时交互'},
    {name:'POP-MCAnimate',               owner:'matthewcheok',desc:'用属性来配置pop动画，方便开发'},
    {name:'popping',                     owner:'schneiderandre',desc:'一个DemoApp，演示用pop实现的各种效果'},
    {name:'AGGeometryKit-POP',           owner:'hfossli',    desc:'一个基于pop的动画，让视图拖动时有橡皮效果 (变形是基于AGGeometryKit)'},
    {name:'MMTweenAnimation',            owner:'adad184',    desc:'基于Pop的动画库，支持各种类型的动画曲线'},
    {name:'CHAnimation',                 owner:'cyndibaby905',desc:'一个小巧的库，用来展示如何构建一个动画引擎 (模仿pop)'},
    {name:'DynamicXray',                 owner:'chrismiles', desc:'用来显示和调试UIKit Dynamics的状态和边界'},
    {name:'AnimationEngine',             owner:'intuit',     desc:'一个用来构建各种复杂动画的库，支持各种动画曲线、弹簧效果等'},
    {name:'NSBKeyframeAnimation',        owner:'NachoSoto',  desc:'那些jQuery带的动画速率曲线'},
    {name:'CAAnimation-EasingEquations', owner:'bryanoltman',desc:'一些CA没有的动画曲线'},
    {name:'UIView-EasingFunctions',      owner:'zrxq',       desc:'UIView的动画曲线~~'},
    {name:'PhysicsAnimation',            owner:'pavelpanov', desc:'物理动画,用Chipmunk实现的重力效果等'},
    {name:'CMTraerPhysics',              owner:'chrismiles', desc:'物理引擎，支持UIKit弹簧/粒子/蜘蛛网/有弹性的布等效果，很棒'},
    {name:'BCMeshTransformView',         owner:'Ciechan',    desc:'很棒的UIView (基于OpenGL渲染),去看看它的博客～'},
    {name:'DPMeterView',                 owner:'dulaccc',    desc:'有重力感应的2D图形动画(例如瓶子的水) 貌似挺有意思～～'},
    {name:'Parallax',                    owner:'acoomans',   desc:'iOS7的景深背景动画效果 一般..'},
    {name:'MTAnimation',        owner:'mysterioustrousers',  desc:'25种动画曲线~~~'},
    {name:'SKBounceAnimation',  owner:'khanlou',             desc:'弹跳的动画曲线'}
    ]
},
{name:'常见动画',
list:[
    {name:'BCGenieEffect',           owner:'Ciechan',      desc:'果冻吸入的效果 和Mac里最小化的效果一样～～很棒~'},
    {name:'VBFJellyView',            owner:'victorBaro',   desc:'基于UIKit Dynamics的果冻效果，很有趣～'},
    {name:'iCarousel',               owner:'nicklockwood', desc:'一套类似CoverFlow的空间,非常棒,可选多样式,可用于Mac'},
    {name:'OpenFlow',                owner:'thefaj',       desc:'类似CoverFlow的效果 挺老的工程 支持Mac'},
    {name:'PaperFold-for-iOS',       owner:'honcheng',     desc:'一套类似报纸展开的仿3D效果 用CA实现'},
    {name:'MPFoldTransition',        owner:'mpospese',     desc:'那个能左右上下Cube/Paper翻页的效果 挺棒'},
    {name:'iOS-Flip-Transform',      owner:'Dillion',      desc:'一个Flip翻页效果 支持上下左右翻页 会变暗'},
    {name:'AFKPageFlipper',          owner:'mtabini',      desc:'一个Flip翻页效果 可能性能不够好 也不会变暗'},
    {name:'DoorwayTransition',       owner:'mkftr',        desc:'一个OpenDoor的动画'},
    {name:'Flipboard-3D-Transform-Effect-Example',owner:'rbreve', desc:'如题Flip效果 没测试'},
    {name:'PaperFoldMenuController', owner:'honcheng',     desc:'一个Map折纸动画效果 一般'},
    {name:'XYOrigami',               owner:'xyfeng',       desc:'Map折纸动画~'},
    {name:'SCSiriWaveformView',      owner:'stefanceriu',  desc:'Siri识别声音时的波浪动画'},
    {name:'Waver',                   owner:'kevinzhow',    desc:'Siri识别声音时的波浪动画 (又一个)'},
    {name:'PaperStack',              owner:'lomanf',       desc:'用OpenGL实现的类似iBook的效果 但是一般'},
    {name:'GCRetractableSectionController', owner:'gcamp', desc:'让TableView能按Group展开合起'},
    {name:'HMGLTransitions',         owner:'Split82',      desc:'一个OpenGL的视图切换 跑不起来? 很久没更新'},
    {name:'EPGLTransitionView',      owner:'epatel',       desc:'一个OpenGL的视图 包括iBook效果 折纸翻页效果 散落效果'},
    {name:'leaves',                  owner:'brow',         desc:'一套有些类似iBook的效果但只有横向翻页 被用在看书的地方'},
    {name:'GC3DFlipTransitionStyleSegue',owner:'GlennChiu',desc:'用GL实现的iBook 一般'},
    {name:'KNSemiModalViewController', owner:'kentnguyen', desc:'一个推出ModalView的动画 后面的会缩小上移'},
    {name:'letterpressexplosion',    owner:'vibrazy',      desc:'UIView的撕碎爆炸效果 (CA实现)'},
    {name:'FancySegue',              owner:'chrismiles',   desc:'几个GL实现的动画 虽然不怎么好'},
    {name:'CoreImageTransition',     owner:'shu223',       desc:'用CI实现的一些动画过渡 过雾～'},
    {name:'LTransitionImageView',    owner:'lukagabric',   desc:'一个Image的过渡效果'},
    {name:'STScratchView',      owner:'SebastienThiebaud', desc:'刮奖的效果'},
    {name:'XBPageCurl',              owner:'xissburg',     desc:'GL实现的翻页效果～'},
    {name:'ADTransitionController',  owner:'applidium',    desc:'很多有趣的导航视图切换动画'},
    {name:'VCTransitionsLibrary',    owner:'ColinEberhardt',desc:'iOS7下，一些自定义转场动画~ 挺棒'},
    {name:'Canvas',                  owner:'CanvasPod',    desc:'在Xcode中直接添加动画'},
    {name:'JazzHands',               owner:'IFTTT',        desc:'IFTTT简介的动画框架，是个关键帧动画框架哟~'}

    ]
},

]
},

{name:'控件',
list:[
{name:'HUD',
list:[
    {name:'MBProgressHUD',            owner:'jdg',               desc:'一个HUD 用得很广泛 无阴影 全屏模态'},
    {name:'MBProgressHUD',            owner:'matej',             desc:'和MBHUD一样 但有更新 添加了BLock iOS6'},
    {name:'JGProgressHUD',            owner:'JonasGessner',      desc:'iOS7音量调节风格的HUD,效果不错'},
    {name:'ATMHud',                   owner:'atomton',           desc:'很棒的HUD 有阴影和动画~'},
    {name:'SVProgressHUD',            owner:'TransitApp',        desc:'一个HUD 样式类似MB_HUD 有一些进度等'},
    {name:'HTProgressHUD',            owner:'Hardtack',          desc:'又一个HUD'},
    {name:'ETActivityIndicatorView',  owner:'EugeneTrapeznikov', desc:'Windows Phone 7风格风火轮'}
    ]
},
{name:'Slider',
list:[
    {name:'JMSlider',                owner:'jasonmorrissey', desc:'一个很小清新的Slider 用CA画的'},
    {name:'ASValueTrackingSlider',   owner:'alskipp',        desc:'滑动出pop显示数字、可变颜色的Slider'},
    {name:'iOS-Custom-Controls',     owner:'mneuwert',       desc:'按住可以出Pop的UISlider'},
    {name:'MTZTiltReflectionSlider', owner:'mdznr',          desc:'一个模仿iOS6 Music的Slider'},
    {name:'ASRangeSlider',           owner:'avrahamshuk',    desc:'一个两段式的Slider'},
    {name:'EFCircularSlider',        owner:'eliotfowler',    desc:'圆环形的slider'},
    {name:'SAMultisectorControl',    owner:'snipter',        desc:'很帅的环形slider'},
    {name:'DCFineTuneSlider',   owner:'domesticcatsoftware', desc:'可以拖动外部 和显示左右箭头的Slider'},
    {name:'ARAnnotatedSlider',       owner:'alexrepty',      desc:'KVO教学 一个在Slider上面显示小Poper的～'},
    {name:'LARSBar',                 owner:'larsacus',       desc:'显示声音dB的Slider'},
    {name:'EDStarRating',            owner:'erndev',         desc:'打星评级 Slider控件'},
    {name:'OBSlider',                owner:'ole',            desc:'模拟iPhone音乐进度的表现'},
    {name:'TLTiltSlider',            owner:'TeehanLax',      desc:'仿iOS6 音量Slider,有金属光泽动画'},
    {name:'RETrimControl',           owner:'romaonthego',    desc:'类似iOS6录像裁减的控制条'}
    ]
},

{name:'Progress',
list:[
    {name:'KOAProgressBar', owner:'mperovic', desc:'自定义ProgressBar'},
    {name:'DDProgressView', owner:'ddeville', desc:'平面风格的Progress进度条'},
    {name:'WNProgressView', owner:'n8chur',   desc:'一些有趣风格的ProgressView'},
    {name:'YLProgressBar',  owner:'YannickL', desc:'一些不错样式的ProgessBar'},
    {name:'DACircularProgress',owner:'danielamitay',desc:'圆环形进度条'},
    {name:'MRProgress',     owner:'mrackwitz',desc:'圆环进度条,iOS7风格,iOS7 Only'},
    {name:'MDRadialProgress',owner:'mdinacci',desc:'圆环进度条,多种风格 iOS6+'},
    {name:'PWProgressView', owner:'pwillsey', desc:'饼形进度条，半透明风格,效果不错'},
    {name:'TWRProgressView',owner:'chasseurmic',desc:'自定义形状Mask的进度'},
    {name:'ASProgressPopUpView',owner:'alskipp',desc:'很简单的，能popup显示进度的条'},
    {name:'M13ProgressSuite',owner:'Marxon13',desc:'一套不同风格的Progress：包括圆形、环形、进度、蒙板等等'},
    {name:'SpinKit-ObjC',   owner:'raymondjavaxx',desc:'由JS版SpinKit模仿得来，几个不错的ActivityIndicator'},
    ]
},




{name:'StatusBar',
list:[
    {name:'JDStatusBarNotification',owner:'jaydee3',  desc:'状态栏控件,支持iOS6、7'},
    {name:'CWStatusBarNotification',owner:'cezarywojcik',desc:'状态栏空间,支持iOS7以上'},
    {name:'MTStatusBarOverlay',  owner:'myell0w',     desc:'状态栏的控件,但很久没更新了'},
    {name:'KGStatusBar',         owner:'kevingibbon', desc:'状态栏控件,提醒'}
    ]
},

{name:'Alert',
list:[
    {name:'BlockAlertsAnd-ActionSheets', owner:'gpambrozio',    desc:'一个Block支持的Alert控件 支持自定义 不错~'},
    {name:'PXAlertView',                 owner:'alexanderjarvis',desc:'一个用来替代系统的Alert,高可定制,有iOS7风格'},
    {name:'MBAlertView',                 owner:'mobitar',       desc:'一个简洁的AlertView,和HUD'},
    {name:'MJPopupViewController',       owner:'martinjuhasz',  desc:'用不同左右动画弹出AlertView'},
    {name:'MZFormSheetController',       owner:'m1entus',       desc:'一个不错的弹出Alert Controller'},
    {name:'WCAlertView',                 owner:'m1entus',       desc:'一些不错的自定义AlertView'},
    {name:'GRAlertView',                 owner:'goncz9',        desc:'用CA画的带颜色的AlertView'},
    {name:'SBTableAlert',                owner:'blommegard',    desc:'一个AlertView 可以带表格 可以用苹果风格'},
    {name:'URBAlertView',                owner:'u10int',        desc:'自定义AlertView 还有各种动画'},
    {name:'SIAlertView',              owner:'Sumi-Interactive', desc:'一个样子不错的自定义AlertView'},
    {name:'MBMenuController',            owner:'MosheBerman',   desc:'一个自定义AlertSheetVC'},
    {name:'JLActionSheet',               owner:'JLoewy',        desc:'另一个自定义AlertSheet'},
    {name:'AMSmoothAlert',               owner:'mtonio91',      desc:'有夸张弹跳效果的Alert'},
    {name:'ASDepthModal',                owner:'autresphere',   desc:'实现简单的3维景深的模态视图 提供背景模糊'},
    {name:'RNBlurModalView',             owner:'rnystrom',      desc:'将后方视图模糊'},
    {name:'NZAlertView',                 owner:'NZN',           desc:'类似notif风格的Alert，拍扁'},
    {name:'LMAlertView',                 owner:'lmcd',          desc:'iOS7 可自定义内容的AlertView'},
    {name:'SDCAlertView',                owner:'sberrevoets',   desc:'iOS7 可自定义内容的AlertView'}
    ]
},

{name:'Notification',
list:[
    {name:'CRToast',            owner:'cruffenach',    desc:'居顶部的notif (状态栏/导航栏)'},
    {name:'EKNotifView',        owner:'ekdevdes',      desc:'很简单的下方Notif实现'},
    {name:'MKInfoPanelDemo',    owner:'MugunthKumar',  desc:'一个从上方滑下的Notif控件 类似TwieetBot'},
    {name:'TSMessages',         owner:'toursprung',    desc:'在导航栏显示一个下拉Notif 效果不错'},
    {name:'CSNotificationView', owner:'problame',      desc:'透明的导航栏下面，滑下的Notif(iOS7)'},
    {name:'YRDropdownView',     owner:'onemightyroar', desc:'类似Tweetbot警告的下伸控件'},
    {name:'NoticeView',         owner:'tciuro',        desc:'类似Tweetbot的下伸控件'},
    {name:'AJNotificationView', owner:'ajerez',        desc:'效果很不错的上部Notif提示'}
    ]
},

{name:'Segment',
list:[
    {name:'NYSegmentedControl',   owner:'nealyoung',   desc:'多种样式和动画的控件，很棒'},
    {name:'SVSegmentedControl',   owner:'samvermette', desc:'一个分段选择控件 类似Mac10.7测试版中的UI 很棒~'},
    {name:'URBSegmentedControl',  owner:'u10int',      desc:'一个灵活的分段控件 可以上下'},
    {name:'MCSegmentedControl',   owner:'oettam',      desc:'一个系统分段的子类 可以自定义颜色'},
    {name:'AKSegmentedControl',   owner:'alikaragoz',  desc:'完全自定义的分段控件 风格不错'},
    {name:'HMSegmentedControl',   owner:'HeshamMegid', desc:'Chrome风格的Tabbar分段'},
    {name:'SDSegmentedControl',   owner:'rs',          desc:'一个离散并且凹陷效果的分段'},
    {name:'DZNSegmentedControl',  owner:'dzenbot',     desc:'可以显示数字的segment，通常用于profile的顶部'},
    {name:'PPiFlatSegmentedControl',owner:'pepibumur', desc:'扁平风格的Segment (包含iOS7样式)'}
    ]
},

{name:'Switch',
list:[
    {name:'DCRoundSwitch', owner:'domesticcatsoftware', desc:'仿UISwicher 可以自定义 很棒'},
    {name:'TTSwitch',      owner:'twotoasters',         desc:'一个可以完全自定义的UISwich～～'},
    {name:'KLSwitch',      owner:'KieranLafferty',      desc:'iOS7风格的Switch 高仿'},
    {name:'MBSwitch',      owner:'mattlawer',           desc:'iOS7风格的Switch 效果多'},
    {name:'SevenSwitch',   owner:'bvogelzang',          desc:'iOS7风格的Switch 效果很多～'}
    ]
},

{name:'Button',
list:[
    {name:'CoolButtons',        owner:'jessmartin',     desc:'用CA画的带Glow的button 仿照系统'},
    {name:'FRDLivelyButton',    owner:'sebastienwindal',desc:'用CA实现的补间动画形状按钮'},
    {name:'VBFPopFlatButton',   owner:'iBaro',          desc:'基于FacebookPop的弹跳形状按钮'},
    {name:'MAConfirmButton',    owner:'mikeahmarani',   desc:'一个类似AppStore下载的按钮 可以动画颜色大小等'},
    {name:'FTWButton',          owner:'FTW',            desc:'一个UIControl实例的Button 可以看到如何自定义控件 有不错的动画效果'},
    {name:'gradientbuttons', owner:'kristopherjohnson', desc:'一个带有不同风格的Button~ 用CA绘制'},
    {name:'DCActionButtonsController', owner:'domesticcatsoftware', desc:'一个PopOver的里面带各种画出的按钮'},
    {name:'BPBarButtonItem',    owner:'BitSuites',      desc:'一个BarItem的不错的on the fly 生成'},
    {name:'BButton',            owner:'mattlawer',      desc:'一种自定义Button 样式类似Twitter的Bootstrap 用CA画的'},
    {name:'OBShapedButton',     owner:'ole',            desc:'用CA绘制的特殊形状button,可以检测path touch'},
    {name:'UIGlossyButton',     owner:'waterlou',       desc:'一些用CA画的带高光的奇怪Button...'}
    ]
},


{name:'Label/Text/排版',
list:[
    {name:'MarqueeLabel',          owner:'cbpowell',        desc:'UILabel跑马灯效果'},
    {name:'Shimmer',               owner:'facebook',        desc:'Facebook Paper中的文本高亮Label,效果类似Slide to unlock'},
    {name:'ICTextView',            owner:'Exile90',         desc:'文本查找,支持正则,关键词高亮'},
    {name:'CoreTextHyperlinkView', owner:'jasarien',        desc:'用CoreText画的 可以带Link的Text'},
    {name:'ZSSRichTextEditor',     owner:'nnhubbard',       desc:'所见即所得富文本编辑，很优秀,支持HTML'},
    {name:'SECoreTextView',        owner:'kishikawakatsumi',desc:'多行富文本TextView,支持图片、可点击链接、编辑等 (也支持OSX)'},
    {name:'EGOTextView',           owner:'enormego',        desc:'UITextField替代品 支持富文本编辑'},
    {name:'iOS-Rich-Text-Editor',  owner:'aryaxt',          desc:'富文本编辑'},
    {name:'MTAnimatedLabel',       owner:'mturner1721',     desc:'类似滑动解锁的闪动Label'},
    {name:'TextGlowDemo',          owner:'andrewgleave',    desc:'一个给Label发出Glow光亮的Demo'},
    {name:'FXLabel',               owner:'nicklockwood',    desc:'一些Label特效,例如阴影描边等'},
    {name:'THLabel',               owner:'MuscleRumble',    desc:'很多Label特效，例如渐变色、阴影、描边等'},
    {name:'AUIAnimatedText',       owner:'adam-siton',      desc:'一个UILabel子类 可以简单动画 颜色大小字体'},
    {name:'RTLabel',               owner:'honcheng',        desc:'简单的富文本Label 可以用Html样式'},
    {name:'TTTAttributedLabel',    owner:'mattt',           desc:'一个Label控件 支持富文本属性'},
    {name:'MDHTMLLabel',           owner:'mattdonnelly',    desc:'一个富文本Label控件,可以支持链接和点击事件'},
    {name:'DTCoreText',            owner:'Cocoanetics',     desc:'CoreText的包装,支持解析Html,支持复杂的排版和图文'},
    {name:'LTCoreText',            owner:'novi',            desc:'基于DTCoreText的TextView,用于显示书，支持CJK竖排版'},
    {name:'OHAttributedLabel',     owner:'AliSoftware',     desc:'支持NSAttributedString的UILabel控件 (目前已不在维护,iOS6以上作者推荐直接用UILabel)'},
    {name:'ARLabel',               owner:'ivankovacevic',   desc:'自动字体大小'},
    {name:'LEffectLabel',          owner:'lukagabric',      desc:'渐变动画颜色的Label,类似滑动解锁'},
    {name:'BBCyclingLabel',        owner:'brunodecarvalho', desc:'在Label发生改变时,有动画效果'},
    {name:'TOMSMorphingLabel',     owner:'TomKnig',         desc:'在Label发生改变时,产生字母的动画效果'},
    {name:'HTAutocompleteTextField',owner:'hoteltonight',   desc:'TextField带自动补全'},
    {name:'JVFloatLabeledTextField',owner:'jverdi',         desc:'带有能浮动的占位符的 文本框'},
    {name:'CMHTMLView',             owner:'mureev',         desc:'用HTML展示富文本,但能有Native类似的体验'},
    {name:'AePubReader',            owner:'fedefrappi',     desc:'一个阅读epub的'},
    {name:'KFEpubKit',              owner:'ricobeck',       desc:'一个epub解析库'}
    ]
},

{name:'PullToRefresh',
list:[
    {name:'UzysAnimatedGifPullToRefresh',   owner:'uzysjung',    desc:'支持用gif呈现的下拉动画'},
    {name:'MSPullToRefreshController',      owner:'bogardon',    desc:'一个不错的上下拉刷新的控件 里面是彩虹'},
    {name:'EGOTableViewPullRefresh',        owner:'enormego',    desc:'下拉刷新,很早的一个控件了几年没更新了,应用广泛'},
    {name:'PullToRefresh',                  owner:'leah',        desc:'下拉刷新'},
    {name:'SVPullToRefresh',                owner:'samvermette', desc:'下拉刷新 扩展了UIScrollView 很方便简单'},
    {name:'HybridRefreshGestureRecognizer', owner:'dingtianran', desc:'一个类似似TweetBot的下拉刷新样式'},
    {name:'sspulltorefresh',                owner:'soffes',      desc:'下拉刷新'},
    {name:'BOZPongRefreshControl',          owner:'boztalay',    desc:'有趣的下拉刷新：下拉出现ping-pong'},
    {name:'CBStoreHouseRefreshControl',     owner:'coolbeet',    desc:'Storehouse中出现的下拉效果，散开/聚拢的闪动的文字'},
    {name:'MJRefresh',                      owner:'CoderMJLee',  desc:'一个据说国内用得比较多的下拉刷新'}
    ]
},

{name:'Scroll/Table',
list:[
    {name:'LRSlidingTableViewCell',    owner:'lukeredpath',    desc:'一个简单的左右滑动Cell 类似Twitter'},
    {name:'TISwipeableTableView',      owner:'thermogl',       desc:'UITable的左右滑动 类似Twitter'},
    {name:'TDBadgedCell',              owner:'tmdvs',          desc:'在TableCell右侧添加badge 有不同风格'},
    {name:'UITableViewZoomController', owner:'TomThorpe',      desc:'类似Google+的 滑动Table缩放显示内部图片'},
    {name:'UITableViewTricks',         owner:'bharath2020',    desc:'TableView的扇形样式'},
    {name:'iPhoneMK',                 owner:'michaelkamprath', desc:'几个简单的自己实现的View和Cell,提供某些常见功能'},
    {name:'EasyTableView',             owner:'alekseyn',       desc:'一个支持左右的TableView 不错～'},
    {name:'ZKRevealingTableViewCell',  owner:'alexzielenski',  desc:'一个简单的可以左右滑动的TableCell'},
    {name:'ADLivelyTableView',         owner:'applidium',      desc:'非常棒的TableCell显示动画～～～'},
    {name:'MHLazyTableImages',         owner:'hollance',       desc:'一个简单的Table加载网络图片 从Apple的例子中改的'},
    {name:'MHPagingScrollView',        owner:'hollance',       desc:'一个可以Page的ScrollView 但可以看到左右的预览 类似WP7'},
    {name:'KLScrollSelect',            owner:'KieranLafferty', desc:'一个竖屏滚动的选择瀑布流'},
    {name:'RNRippleTableView',         owner:'rnystrom',       desc:'Cell梳子抖动~ 挺有创意'},
    {name:'RETableViewManager',        owner:'romaonthego',    desc:'数据驱动的Table 由数据画出Table内容'},
    {name:'FXForms',                   owner:'nicklockwood',   desc:'快速构建Table Based表单/设置界面'},
    {name:'XLForm',                    owner:'xmartlabs',      desc:'强大的table/表单/设置 的构建工具'},
    {name:'ios-SDNestedTable',         owner:'serverdensity',  desc:'二级菜单的Table'},
    {name:'SWTableViewCell',           owner:'CEWendel',       desc:'类似iOS7邮件中的Cell,左右滑动出现多个功能键'},
    {name:'NJKScrollFullScreen',       owner:'ninjinkun',      desc:'Nav内容滑动时，自动隐藏上下两个导航栏'},
    {name:'AMScrollingNavbar',         owner:'andreamazz',     desc:'Nav内容滑动时，自动隐藏上方导航栏'},
    {name:'TSUIKit',                   owner:'Viacheslav-Radchenko',desc:'复杂数据表格、tab展示的UI控件，适合复杂数据展示'}
    ]
},

{name:'Popover',
list:[
    {name:'PopoverView',        owner:'runway20',    desc:'CA实现的Popover 可用于iPhone,样式清新'},
    {name:'WYPopoverController',owner:'nicolaschengdev',desc:'高可定制Popover 样式不错，很棒'},
    {name:'CMPopTipView',       owner:'chrismiles',  desc:'把PopView带入的iPhone'},
    {name:'FPPopover',          owner:'50pixels',    desc:'一个PopOver 支持iPhone'},
    {name:'WEPopover',          owner:'werner77',    desc:'一个仿Popover API库 支持iPhone'},
    {name:'UAModalPanel',       owner:'UrbanApps',   desc:'一个类似PopView控件 可以比较多的自定义 Demo样式较乱'},
    {name:'ColorPopover',       owner:'gazolla',     desc:'一个用WEPopover写的单色选择'},
    {name:'MultiRowCalloutAnnotationView', owner:'grgcombs', desc:'在Map里面弹出带表格的Pop'},
    {name:'QBPopupMenu',        owner:'questbeat',   desc:'类似iOS文字上的Pop 可以自定义~'},
    {name:'kxmenu',             owner:'kolyvan',     desc:'一个PopView,动作还可以'},
    {name:'RNGridMenu',         owner:'rnystrom',    desc:'一个Pop菜单，有背景模糊，效果不错～'},
    {name:'CNPPopupController', owner:'carsonperrotti',desc:'模态弹出框，有很多自定义选项'},
    {name:'GIKPopoverBackgroundView', owner:'GiK',   desc:'为PopOver提供无缝背景 很棒'},
    {name:'AwesomeMenu',        owner:'levey',       desc:'Path的扇形弹出按钮效果(CA)'},
    {name:'QuadCurveMenu',      owner:'levey',       desc:'上面AwesomeMenu的fork 类似Path的菜单'},
    {name:'MGTileMenu',         owner:'mattgemmell', desc:'弹出按钮菜单 在四周成方形 效果不错'},
    {name:'ADPopupView',     owner:'Antondomashnev', desc:'在UIVIew上弹出自己画的界面 挺丑 但可以看看实现'},
    {name:'KLExpandingSelect',owner:'KieranLafferty',desc:'四叶草风格弹出菜单~'},
    {name:'StackMenu',          owner:'istsest',     desc:'Mac的Stack弹出菜单'}
    ]
},

{name:'GridView',
list:[
    {name:'AQGridView',         owner:'AlanQuatermain', desc:'类似TableView但有横向分类,就像Android Launcher'},
    {name:'GMGridView',         owner:'gmoledina',      desc:'又一个GridView 很不错,自带横纵排序编辑等功能'},
    {name:'KKGridView',         owner:'kolinkrewinkel', desc:'又一个GridView 已经Deperacted 直接用系统的就好'},
    {name:'A3GridTableView',    owner:'allaboutapps',   desc:'又一个GridView 貌似支持类似图标样的上栏'},
    {name:'LIExposeController', owner:'linkedin',       desc:'一个类似GridView的东西'}
    ]
},


{name:'界面切换/导航',
list:[
    {name:'LTNavigationBar',               owner:'ltebean',        desc:'随Scroll自动渐隐渐显的NavBar Category'},
    {name:'BLKFlexibleHeightBar',          owner:'bryankeller',    desc:'随Scroll自动渐隐渐显的NavBar，支持各种过度效果'},
    {name:'APExtendedPageController',      owner:'niktszczegolny', desc:'类似Chrome左右滑动切换视图的控件'},
    {name:'MBSpacialViewController',       owner:'mobitar',        desc:'2D上下左右导航的奇怪视图'},
    {name:'MSMatrixController',            owner:'MarcoSero',      desc:'又一个 2D上下左右导航的奇怪视图..'},
    {name:'MHTabBarController',            owner:'hollance',       desc:'一个类似Android的上方Tabbar'},
    {name:'FSVerticalTabBarController',    owner:'futuresimple',   desc:'在左侧的Tabbar'},
    {name:'AKTabBarController',            owner:'alikaragoz',     desc:'自定义Tabbar 样式类似AppStore'},
    {name:'MGSplitViewController',         owner:'mattgemmell',    desc:'类似系统的UISplitVC 但有更多功能'},
    {name:'PSTCollectionView',             owner:'steipete',       desc:'100%兼容UICollectionView的空间 为了支持iOS4.3'},
    {name:'AMWaveTransition',              owner:'andreamazz',     desc:'两个TableView之间的导航，果冻抖动效果'},
    {name:'JMTabView',                     owner:'jasonmorrissey', desc:'一个TabView 用CA画的,类似 Mac系统的单选控件'},
    {name:'MWFSlideNavigationViewController', owner:'meiwin',      desc:'一个能左右上下滑动的简单导航栏'},
    {name:'ZFDragableModalTransition',     owner:'zoonooz',        desc:'弹出Modal Controller的动画，效果还可以'},
    {name:'UIScrollSlidingPages',          owner:'TomThorpe',      desc:'一个和Chrome类似的左右滑动Pager'},
    {name:'FlipBoardNavigationController', owner:'michaelhenry',   desc:'类似网易客户端/Flipboard手机 左右滑动的Nav'},
    {name:'BCTabBarController',            owner:'briancollins',   desc:'Twitter类似的Tabbar 2年前的工程'},
    {name:'CKSideBarController',           owner:'jaykz52',        desc:'类似Twitter iPad的左侧Tabbar'},
    {name:'DVSlideViewController',         owner:'dickverbunt',    desc:'类似Safari的滑动切换'},
    {name:'HGPageScrollView',              owner:'100grams',       desc:'类似Safari浏览的分页控件、'},
    {name:'HSImageSidebarView',            owner:'bjhomer',        desc:'一个类似Keynote的侧边栏'},
    {name:'CBHazeTransitionViewController',owner:'coolbeet',       desc:'类似iOS6的下拉刷新的动画切换，水滴状拖拽'},
    {name:'JTMaterialTransition',          owner:'jonathantribouharet',desc:'Android Material 转场效果 (圆形放大至全屏)'},
    {name:'KYPingTransition',              owner:'KittenYang',     desc:'Android Material 转场 Transition (圆形放大至全屏)'},
    {name:'RNSwipeViewController',         owner:'rnystrom',       desc:'滑动界面显示另一个界面 类似下拉状态栏查看天气'},
    {name:'RESideMenu',                    owner:'romaonthego',    desc:'iOS7风格侧滑'},
    {name:'SloppySwiper',                  owner:'fastred',        desc:'全屏左滑返回'},
    {name:'MLTransition',                  owner:'molon',          desc:'全屏左滑返回,效果完善,不用截屏'},
    {name:'MultiLayerNavigation',          owner:'vinqon',         desc:'全屏左滑返回,用截屏实现'}
    ]
},

{name:'侧滑',
list:[
    {name:'ViewDeck',                owner:'Inferis',    desc:'左右侧滑控件'},
    {name:'MSDynamicsDrawerViewController',owner:'monospacecollective',desc:'iOS7 动态弹性和景深的侧滑～'},
    {name:'ECSlidingViewController', owner:'ECSlidingViewController',   desc:'一个很简单的侧滑控件'},
    {name:'JASidePanels',            owner:'gotosleep',  desc:'一套不错样式的侧滑控件'},
    {name:'PSStackedView',           owner:'steipete',   desc:'一套侧滑且带Stack的控件,类似Twitter iPad'},
    {name:'PKRevealController',      owner:'pkluz',      desc:'一个侧滑控件'},
    {name:'JTRevealSidebarDemo',     owner:'jamztang',   desc:'一个类似FB侧滑的Demo'},
    {name:'PPRevealSideViewController', owner:'ipup',    desc:'又一个类似FB的侧滑控件'},
    {name:'CLCascade',               owner:'appunite',   desc:'类似Twitter iPad版的侧滑控件'},
    {name:'MMDrawerController',    owner:'mutualmobile', desc:'一个侧滑控件'},
    {name:'MFSideMenu',            owner:'mikefrederick',desc:'Facebook风格侧滑'},
    {name:'SWRevealViewController',owner:'John-Lluch',   desc:'Facebook风格侧滑'},
    {name:'DDMenuController',      owner:'devindoty',    desc:'又是一个Facebook风格侧滑'},
    {name:'REFrostedViewController', owner:'romaonthego',desc:'一个iOS7风格的毛玻璃侧滑菜单'},
    {name:'AMSlideMenu',            owner:'SocialObjects-Software',    desc:'类似GoogleMap的侧滑'},
    {name:'RNFrostedSidebar',       owner:'rnystrom',    desc:'一个由侧面划出的半透明菜单(小圆片),不错的交互效果'}
    ]
},

{name:'知名效果Demo',
list:[
    {name:'KLNoteViewController',         owner:'KieranLafferty',desc:'一个类似Evernote旧版的Stack界面 绿色的'},
    {name:'REComposeViewController',      owner:'romaonthego',   desc:'一个类似系统Twitter分享界面~'},
    {name:'DETweetComposeViewController', owner:'doubleencore',  desc:'一个iOS4实现的 类似iOS5的twitter分享'},
    {name:'JTGestureBasedTableViewDemo',  owner:'jamztang',     desc:'一个类似Clear的Demo'},
    {name:'Opaque',                       owner:'MassiveHealth', desc:'一个Clear的Demo'},
    {name:'MCSwipeTableViewCell',         owner:'alikaragoz',    desc:'类似Mailbox的控件 和Clear差不多'},
    {name:'CHTCollectionViewWaterfallLayout',owner:'chiahsien',  desc:'瀑布流控件'},
    {name:'PSCollectionView',             owner:'ptshih',        desc:'类似瀑布流式的控件'},
    {name:'IIIThumbFlow',                owner:'sehone',         desc:'瀑布流控件'},
    {name:'WaterflowView',              owner:'aceisScope',      desc:'瀑布流的View 看样子Star挺多'},
    {name:'KNPathTableViewController', owner:'kentnguyen',       desc:'在Table右侧显示类似Path的时间 很简单~'},
    {name:'GSBookShelf',            owner:'ultragtx',            desc:'一个类似iBook书柜的实现'},
    {name:'M6ParallaxController', owner:'peterpaulis',             desc:'类似Path封面的效果'},
    {name:'ZGParallelView',       owner:'zhigang1992',           desc:'类似Path的封面效果 貌似不错'},
    {name:'TimeScroller',         owner:'andrewroycarter',       desc:'类似Path右侧的时间小滑块'},
    {name:'THSpringyCollectionView',owner:'tristanhimmelman',    desc:'iOS7短信泡泡滑动时有弹性的效果'},
    {name:'chatheads',            owner:'brutella',              desc:'Facebook 一个一直最上方的头像 点击可以显示Table'},
    {name:'MBSliderView',         owner:'mattlawer',             desc:'滑动解锁'},
    {name:'DKLiveBlur',           owner:'kronik',                desc:'雅虎天气风格的动态模糊'},
    {name:'ios-realtimeblur',     owner:'alexdrone',             desc:'iOS7 模糊效果'},
    {name:'GHSidebarNav',         owner:'gresrun',               desc:'新版Facebook 侧滑等UI'},
    {name:'LXReorderableCollectionViewFlowLayout',owner:'lxcid', desc:'iBook中 拖动图书的功能'},
    {name:'MDCParallaxView',      owner:'modocache',             desc:'景深效果 就像Path的封面那样'},
    {name:'CRMotionView',         owner:'chroman',               desc:'Facebook Paper里面，跟随手势左右翻动的图片页面'}
    ]  
},


{name:'高级功能',
list:[
    {name:'mapbox-gl-native',          owner:'mapbox',      desc:'mapbox开源的矢量地图 (很庞大的库)'},
    {name:'PAPasscode',                owner:'dhennessy',   desc:'类似系统的输入密码界面'},
    {name:'KKPasscodeLock',            owner:'aporat',      desc:'又一个类似系统输入密码界面'},
    {name:'PTShowcaseViewController',  owner:'exalted',     desc:'能显示音视频等一堆格式文件的控件'},
    {name:'Reader',                    owner:'vfr',         desc:'一套显示PDF的库 支持大文件、加密文件 有iBook样式的界面 性能很好'},
    {name:'FastPdfKit',                owner:'mobfarm',     desc:'一套PDF库 性能据说很好 也有界面'},
    {name:'M13PDFKit',                 owner:'Marxon13',    desc:'PDF显示的库，有iBook样式的缩略图'},
    {name:'Kal',                       owner:'klazuka',     desc:'一套日历控件 高仿iOS默认'},
    {name:'objc-TimesSquare',          owner:'square',      desc:'一套日历控件 类似iOS默认 貌似清新一些'},
    {name:'ABCalendarPicker',          owner:'k06a',        desc:'高仿iOS默认日历的DatePicker~'},
    {name:'EBPhotoPages',              owner:'EddyBorja',   desc:'图片浏览控件，提供类似Facebook browser类似的功能'},
    {name:'MWPhotoBrowser',            owner:'mwaterfall',  desc:'一套图片浏览控件 高仿iOS默认 支持网络图片'},
    {name:'PTImageAlbumViewController',owner:'exalted',     desc:'图片浏览控件 仿iOS默认'},
    {name:'FGallery-iPhone',           owner:'gdavis',      desc:'图片浏览器'},
    {name:'AGImagePickerController',   owner:'arturgrigor', desc:'选取图片 支持多选'},
    {name:'ELCImagePickerController',  owner:'B-Sides',     desc:'一个仿系统的ImagePicker 但支持多选'},
    {name:'PhotoViewer',               owner:'enormego',    desc:'一个图片浏览的控件'},
    {name:'KTPhotoBrowser',            owner:'kirbyt',      desc:'图片浏览控件 3年没更新了'},
    {name:'DLCImagePickerController',  owner:'gobackspaces',desc:'一个用GPUImage实现的 ImagePicker功能,支持拍照和特效'},
    {name:'route-me',                  owner:'route-me',    desc:'一套自定义MapView 高仿系统 但支持不同的数据源'},
    {name:'SlackTextViewController',   owner:'slackhq',     desc:'类似短信发送的界面'},
    {name:'GrowingTextView',           owner:'HansPinckaers',desc:'一个高仿短信发送的输入框'},
    {name:'PHFComposeBarView',         owner:'fphilipe',    desc:'高仿短信发送输入框'},
    {name:'JSQMessagesViewController', owner:'jessesquires',desc:'高仿iOS7短信界面,可定制,支持文本、图片、视频，效果不错'},
    {name:'Chats',                     owner:'acani',       desc:'仿短信App (Swift)'},
    {name:'UIBubbleTableView',         owner:'AlexBarinov', desc:'iOS短信的泡泡界面,可以支持图片'},
    {name:'ODRefreshControl',          owner:'Sephiroth87', desc:'一个高仿iOS6下拉刷新的控件(橡皮条)'},
    {name:'ssmessagesviewcontroller',  owner:'soffes',      desc:'和系统类似的发短信界面 挺粗糙 当然现在系统已经提供了'},
    {name:'SVWebViewController',       owner:'TransitApp',  desc:'一个简易的浏览器功能控件'},
    {name:'TSMiniWebBrowser',          owner:'tonisalae',   desc:'一个简易的内置浏览器'},
    {name:'TITokenField',              owner:'thermogl',    desc:'一个高仿Mail和短信 选择联系人的控件'},
    {name:'DAAppsViewController',      owner:'danielamitay',desc:'一个仿AppStore的列表界面 输入appId集合'},
    {name:'WUEmoticonsKeyboard',       owner:'YuAo',        desc:'输入表情的自定义键盘'},
    {name:'CKCalendar',                owner:'jaykz52',     desc:'一个朴实的日历'},
    {name:'Cool-iOS-Camera',           owner:'GabrielAlva', desc:'自定义拍照Ctrl'},
    {name:'TGCameraViewController',    owner:'tdginternet', desc:'一个不错的拍照Ctrl'},
    {name:'SCRecorder',                owner:'rFlex',       desc:'一个不错的录像Ctrl，支持实时切换滤镜'},
    {name:'LBYouTubeView',             owner:'larcus94',    desc:'显示Youtube视频..国内无用'},
    {name:'JustType',                  owner:'tonqa',       desc:'Keyboard扩展，手势支持等'}
    ]
},
{name:'套装',
list:[
    {name:'tapkulibrary',    owner:'devinross',  desc:'一套比较大的自定义控件库 包括不错的HUD,进度条,日历,CoverFlow等'},
    {name:'FlatUIKit',       owner:'Grouper',    desc:'一套完整的扁平风格的UI  (Flat)'},
    {name:'FlatUI',          owner:'piotrbernad',desc:'一套仿iOS7的控件'},
    {name:'UI7Kit',          owner:'youknowone', desc:'一套iOS7风格的控件,可以在iOS5、6上用'},
    {name:'PrettyKit',       owner:'vicpenap',   desc:'一套系统UI的子类 有着平滑渐变和阴影效果'},
    {name:'nui',             owner:'tombenner',  desc:'一套加在UIKit上的Category,允许用类CSS代码来控制样式'},
    {name:'QuickDialog',     owner:'escoz',      desc:'一套自定义控件库,用来快速建造基于Table的设置'},
    {name:'MGBoxKit',        owner:'sobri909',   desc:'一套UIView的扩展和子类(Table Grid..) 有不错的类CSS的功能 有些好用的代码'},
    {name:'MGBox',           owner:'sobri909',   desc:'MGBox的旧版 应该去看v2'},
    {name:'iOS-boilerplate', owner:'gimenete',   desc:'一些常见功能实现的例子:HUD Table滑动,打开URL用WebView等 挺老的工程'},
    {name:'idev-recipes',    owner:'boctor',     desc:'iDevRecipes博客的代码,演示了如何自定义一些控件,代码比较老..'}
    ]
},
{name:'其他',
list:[
    {name:'SMPageControl',       owner:'Spaceman-Labs',   desc:'一个仿UIPageControl的API类 可以自定义小点点～'},
    {name:'REActivityViewController',owner:'romaonthego', desc:'开的ActivityView实现'},
    {name:'DCControls',      owner:'domesticcatsoftware', desc:'不错的扇形滑动控件 平面风格'},
    {name:'BSKeyboardControls',  owner:'simonbs',         desc:'与键盘相关的控制 控制 上一项下一项'},
    {name:'FBAnnotationClustering',owner:'infinum',       desc:'一个MapKit上显示多个地点自动聚合的东西'},
    {name:'OCMapView',           owner:'yinkou',          desc:'一个MapKit标注聚合用的东西～'},
    {name:'NJKWebViewProgress',  owner:'ninjinkun',       desc:'显示WebView加载进度'},
    {name:'REMenu',              owner:'romaonthego',     desc:'一个导航栏下拉菜单 不错～'},
    {name:'action-sheet-blocks', owner:'MugunthKumar',    desc:'为ActionSSheet提供block方法'},
    {name:'ADClusterMapView',    owner:'applidium',       desc:'Map的地标Cluster 应该不错～'},
    {name:'TPKeyboardAvoiding',  owner:'michaeltyson',    desc:'一个UIView的 在有键盘时上移'},
    {name:'calloutview',         owner:'nfarina',         desc:'实现了私有的UICalloutView 类似地图中的弹出控件'},
    {name:'SVPulsingAnnotationView', owner:'samvermette', desc:'一个自定义MapLocator 动画控件'},
    {name:'OWActivityViewController', owner:'brantyoung', desc:'一个类似系统的分享控件'},
    {name:'SYEmojiPopover',      owner:'dvkch',           desc:'显示一个Emoji选择de PopOVer'},
    {name:'fingertips',          owner:'developmentseed', desc:'在屏幕上显示触摸点 只支持iPad2和iPhone4s以上'},
    {name:'ASTouchVisualizer',   owner:'autresphere',     desc:'为屏幕触摸添加指示 可用于屏幕录制'},
    {name:'openspringboard',     owner:'fieldforceapp',   desc:'仿SpringBoard的东西'},
    {name:'HMLauncherView',      owner:'heikomaass',      desc:'仿SpringBoard的东西'},
    {name:'CQMFloatingController', owner:'cocopon',       desc:'一个浮动的VC 类似Popover(没有箭头) 可以用在横屏iPhone等'},
    {name:'WSCoachMarksView',    owner:'workshirt',       desc:'为某个控件加上蒙板 类似Spotlight'},
    {name:'COSTouchVisualizer',  owner:'conopsys',        desc:'在屏幕上显示手指的触摸事件'},
    {name:'KLHorizontalSelect',  owner:'KieranLafferty',  desc:'横向扫动选择'},
    {name:'KYGooeyMenu',         owner:'KittenYang',      desc:'类似 Path 的带黏性的菜单'},
    {name:'KYCuteView',          owner:'KittenYang',      desc:'类似 QQ 那样，拖拽能拽走的小球'},
    {name:'iOS-StyledPageControl', owner:'honcheng',      desc:'自定义PageControl,多种样式'},
    {name:'iOS-blur',            owner:'ArcticMinds',     desc:'iOS7的模糊效果 iOS7Only'},
    {name:'FXBlurView',          owner:'nicklockwood',    desc:'iOS7的模糊效果 可以用在iOS5以上'},
    {name:'LiveFrost',           owner:'radi',            desc:'View动态模糊效果,思路和效果都不错，性能稍差'},
    {name:'CRGradientNavigationBar',owner:'chroman',      desc:'iOS7状态栏 过渡的颜色'},
    {name:'MYBlurIntroductionView', owner:'MatthewYork',   desc:'带有模糊背景效果的 Intro'},
    {name:'MLPAccessoryBadge',   owner:'EddyBorja',       desc:'一些自定义badge~'},
    {name:'JSBadgeView',         owner:'JaviSoto',        desc:'数字角标 Badge'},
    {name:'DKNightVersion',      owner:'Draveness',       desc:'夜间模式'},
    {name:'Context-Menu.iOS',    owner:'Yalantis',        desc:'一个动画效果不错的下拉菜单'},
    {name:'FoldingTabBar.iOS',   owner:'Yalantis',        desc:'一个动画效果不错的，可以收起的Tabbar'},
    {name:'MSCellAccessory',     owner:'bitmapdata',      desc:'Cell右侧的小箭头~'},
    {name:'ios-fontawesome',     owner:'alexdrone',       desc:'一套用字体实现的Icon'},
    {name:'WTGlyphFontSet',      owner:'waterlou',        desc:'另一套用字体实现的Icon'},
    {name:'DAKeyboardControl',   owner:'danielamitay',    desc:'键盘滑动消逝，就像系统内置的短信界面'},
    {name:'JWFolders',           owner:'jwilling',        desc:'iOS6以下的文件夹展开效果'},
    {name:'OCCalendar',          owner:'ocrickard',       desc:'Popover样式的日期选择器'},
    {name:'IBAForms',            owner:'ittybittydude',   desc:'Form构建。2年前的工程了..'},
    {name:'ActionSheetPicker-3.0',owner:'skywinder',      desc:'用Popover显示的Picker'},
    {name:'MSCollectionViewCalendarLayout',owner:'monospacecollective',desc:'日历事件样式 iOS6以上'},
    {name:'MosaicUI',            owner:'betzerra',        desc:'WP7磁片风格View 自适应大小'},
    {name:'MosaicLayout',        owner:'TwoTinedFork',    desc:'WP7磁片风格Layout UICollectionView'},
    {name:'iPhone-IntroductionTutorial',owner:'MatthewYork',desc:'用于创建启动引导界面的...'},
    {name:'US2FormValidator',    owner:'ustwo',           desc:'一套Table表单验证提示'},
    {name:'AURosetteView',       owner:'emilwojtaszek',   desc:'玫瑰花瓣似的展开菜单'},
    {name:'YRActivityIndicator', owner:'solomidSF',       desc:'一个挺有意思的Loading动画,支持 Interface Builder 调节'},
    {name:'PQFCustomLoaders',    owner:'poolqf',          desc:'很多不同风格的Loading动画，挺有意思'},
    {name:'EAIntroView',         owner:'ealeksandrov',    desc:'App启动的介绍界面'},
    {name:'Onboard',             owner:'mamaral',         desc:'App启动引导'},
    {name:'PEPhotoCropEditor',   owner:'kishikawakatsumi',desc:'图片裁切的工具，类似系统的图片App'},
    {name:'InformaticToolbar',   owner:'gregwym',         desc:'下边栏显示提示和动作'},
    {name:'CCHMapClusterController',owner:'choefele',     desc:'自动归类MapKit上面的标记'},
    {name:'JTSImageViewController',owner:'jaredsinclair', desc:'点击弹出图片，双击缩放，再点击缩回原处，这种常见的功能...'},
    {name:'FLXView',             owner:'robb',            desc:'以 flexbox 方式布局'}
    ]
}

]
},





{name:'较完整的App',
list:[
    {name:'ResearchKit',        owner:'ResearchKit',    desc:'苹果官方开源的医疗相关的库,其中有基于它制作的4款独立App,文档完整,支持appledoc,有非常好的参考价值'},
    {name:'Brushes',            owner:'sprang',         desc:'绘画的App,超棒,Appstore上架应用'},
    {name:'Inkpad',             owner:'sprang',         desc:'一个完整的矢量绘图App，很棒，已上架'},
    {name:'apps-ios-wikipedia', owner:'wikimedia',      desc:'维基百科官方App, 已上架'},
    {name:'viewfinder',         owner:'viewfinderco',   desc:'Square开源了完整的viewfinder源码，包括服务端和客户端(iOS/Android) 赞！'},
    {name:'modizer',            owner:'yoyofr',         desc:'很强大的App 可以读取和演奏各种mod音乐 midi合成 解压 下载 自带庞大音乐库~ 已上架'},
    {name:'NOTTaskPaperForIOS', owner:'jessegrosjean',  desc:'TaskPaper源码~'},
    {name:'GraphSketcher',      owner:'graphsketcher',  desc:'以OmniGroup为基础，做的类似OneNote的工具，支持Mac和iPad'},
    {name:'Sol',                owner:'comyarzaheri',   desc:'漂亮的扁平风格的天气 App'},
    {name:'ESTMusicPlayer',     owner:'Aufree',         desc:'一个界面不错的音乐播放器 App'},
    {name:'ChatSecure-iOS',     owner:'chrisballinger', desc:'一个XMPP客户端～ 支持Jabber/GTalk等XMPP协议'},
    {name:'iOSSF',              owner:'gaosboy',        desc:'SegmentFault官方App ...'},
    {name:'PlainReader',        owner:'guojiubo',       desc:'CnBeta简阅,简洁好用的CB客户端,曾上架AppStore但因版权问题被下了'},
    {name:'ioctocat',           owner:'dennisreimann',  desc:'一个Github客户端'},
    {name:'trailer',            owner:'HouseTrip',      desc:'保持Github在线～ 包括iOS/OSX客户端'},
    {name:'LayerPlayer',        owner:'scotteg',        desc:'一个用来展示CoreAnimation功能的App，已上架AppStore'},
    {name:'eigen',              owner:'artsy',          desc:'浏览世界上的艺术名作, 已上架AppStore'},
    {name:'Doppio',             owner:'chroman',        desc:'寻找最近的星巴克'},
    {name:'cheddar-ios',        owner:'nothingmagical', desc:'一个日程管理的App 应该比较知名'},
    {name:'Bible-Assistant',    owner:'nixzhu',         desc:'圣经小助手，已上架'},
    {name:'AppSales-Mobile',    owner:'omz',            desc:'基于iTunes Connect来查看App销售状况'},
    {name:'canabalt-ios',       owner:'ericjohnson',    desc:'一个跑步的小游戏～'},
    {name:'baker',              owner:'Simbul',         desc:'一套HTML5构建的ebook库 貌似挺强大'},
    {name:'iPhoneTracker',      owner:'petewarden',     desc:'一个挺老的App 2年前'},
    {name:'Off-the-Record-iOS', owner:'chrisballinger', desc:'一个实时聊天的功能 支持一些XMPP协议'},
    {name:'kokuban',            owner:'u-mizo',         desc:'一个iPad小画板 3年前'},
    {name:'glpaint',            owner:'nskboy',         desc:'从Appled的GLPaint改的'},
    {name:'OpenGLMilkyWay',     owner:'hannorein',      desc:'银河～～ 很棒 有教材'},
    {name:'iphone-app',         owner:'oschina',        desc:'OSChina 开源中国 ..竟然挪到git.oschina.net去了。。'},
    {name:'BeeFancy',           owner:'BeeFramework',   desc:'一个仿Fancy的客户端 基于BeeFranework'},
    {name:'ruby-china-for-ios', owner:'ruby-china',     desc:'RubyChina官方客户端'},
    {name:'ruby-china-ios',     owner:'daveliu',        desc:'和上面一样?'},
    {name:'wh-app-ios',         owner:'WhiteHouse',     desc:'白宫官方App'},
    {name:'CastleHassle',       owner:'bryceredd',      desc:'一个Cocos2D的物理小游戏 貌似内容挺丰富～'},
    {name:'DocSets-for-iOS',    owner:'omz',            desc:'iOS显示DocSets 可以下载iOS官方Doc~'},
    {name:'newsyc',             owner:'Xuzz',           desc:'一个newsyc.me的客户端 (iPhone hacker News)'},
    {name:'Upcoming',           owner:'TeehanLax',      desc:'一个设计很棒的日程安排'},
    {name:'Anypic',             owner:'ParsePlatform',  desc:'一个像Instagram那样的图片分享社区App'},
    {name:'ClassicMap',        owner:'kishikawakatsumi',desc:'旧版iOS地图'},
    {name:'ntlniph',            owner:'takuma104',      desc:'Twitter客户端 古老的工程了'},
    {name:'lastfm-iphone',      owner:'c99koder',       desc:'Last.fm官方客户端'},
    {name:'FFCalendar',         owner:'fggeraissate',   desc:'iPad日历，类似iOS7的日历。有些粗糙'},
    {name:'ThatInbox',          owner:'Ink',            desc:'Ink出的邮件客户端'},
    {name:'ThatCloud',          owner:'Ink',            desc:'Ink出的云端文件管理'},
    {name:'ThatPDF',            owner:'Ink',            desc:'Ink出的PDF编辑'},
    {name:'ThatPhoto',          owner:'Ink',            desc:'Ink出的图片编辑'}
    ]
},


{name:'开发/调试/统计',
list:[
    {name:'xctool',           owner:'facebook',          desc:'Facebook iOS工程构建和测试工具,用于替代系统的xcodebuild  (CI)'},
    {name:'origami',          owner:'facebook',          desc:'Facebook Paper用到的原型设计工具,是Quartz Composer插件'},
    {name:'Tweaks',           owner:'facebook',          desc:'Facebook Paper用到的界面调整小工具,可以给产品/开发自己去调整和尝试动画/颜色等'},
    {name:'ios-snapshot-test-case',owner:'facebook',     desc:'Facebook 的iOS单元测试工具,通过截屏对比来实现UI测试'},
    {name:'chisel',           owner:'facebook',          desc:'Facebook 出的一套LLDB增强命令, 注意这是python脚本'},
    {name:'plcrashreporter',  owner:'plausiblelabs',     desc:'在客户端捕获、生成crash log并上传的库，很棒！详情去官网看'},
    {name:'QuincyKit',        owner:'TheRealKerni',      desc:'自动生成和上传crash log，并可以在页面查看。包含Server/Client代码，依赖上面那个库'},
    {name:'BugshotKit',       owner:'marcoarment',       desc:'上报bug的工具,支持截屏和Log (不要在AppStore上架时用)'},
    {name:'PonyDebugger',     owner:'square',            desc:'一套Debugger工具,可以在电脑浏览器上远程调试iOS程序～查看试图层次、网络等'},
    {name:'NSLogger',         owner:'fpillet',           desc:'一套Log工具,可以在电脑上通过client实时查看NSLog,甚至是图片和二进制文件 支持Android'},
    {name:'KIF',              owner:'kif-framework',     desc:'一套用Private API做的调试库,可以以用户的方式测试(touch in xxx)'},
    {name:'gh-unit',          owner:'gabriel',           desc:'一套ObjC的测试框架'},
    {name:'WBWebViewConsole', owner:'Naituw',            desc:'App内调试WebView的终端'},
    {name:'SimulatorRemoteNotifications',owner:'acoomans',desc:'模拟远程Push的工具，调试APNS用'},
    {name:'FLEX',             owner:'Flipboard',         desc:'Flipboardc出的一个在App内调试和和实时修改的工具，很棒~'},
    {name:'DCIntrospect',    owner:'domesticcatsoftware',desc:'一套iOS调试工具,在iOS界面里显示信息'},
    {name:'CocoaLumberjack',  owner:'CocoaLumberjack',   desc:'一套类似Log4j的东西,可提供企业级的Log~~~~'},
    {name:'UALogger',         owner:'UrbanApps',         owner:'一个调试用Log工具,支持分级'},
    {name:'ios-class-guard',  owner:'Polidea',           owner:'iOS 代码混淆工具'},
    {name:'class-dump',       owner:'nygard',            owner:'class dump 嗯。。'},
    {name:'ARAnalytics',      owner:'orta',              desc:'用户行为统计，支持各大App数据平台'},
    {name:'SkyLab',           owner:'mattt',             desc:'A/B Test工具～'},
    {name:'HeapInspector-for-iOS',owner:'tapwork',       desc:'测试和定位内存泄露的库'},
    {name:'RHObjectiveBeagle',owner:'heardrwt',          desc:'追踪内存中对象状态的库'},
    {name:'Xtrace',           owner:'johnno1962',        desc:'输出所有的方法调用消息 (可以按instance/class过滤)'},
    {name:'Frank',            owner:'moredip',           desc:'自动化测试工具？'},
    {name:'dSYMTools',        owner:'answer-huang',      desc:'MacApp,通过dSYM文件解析崩溃log'},
    {name:'umeng-crash-symbol',owner:'Quotation',        desc:'Mac脚本,解析友盟的崩溃Log'},
    {name:'superdb',          owner:'Shopify',           desc:'一个Debuger工具 用命令行调试。。'},
    {name:'iOS-Hierarchy-Viewer', owner:'glock45',       desc:'一个调试iOS界面的工具 通过浏览器访问~~ 值得瞅瞅～～'},
    {name:'hierarchydetective',owner:'chinmaygarde',     desc:'一个3D显示iOS视图层级的调试工具'},
    {name:'CATransform3D-Test',owner:'honcheng',         desc:'调试CATransform3D矩阵的工具～'},
    {name:'LLDB-QuickLook',   owner:'ryanolsonk',        desc:'在调试时用命令行调用QuickLook来显示图片、UIView等'},
    {name:'iConsole',         owner:'nicklockwood',      desc:'在App内显示调试信息、执行调试命令'},
    {name:'Nocilla',          owner:'luisobo',           desc:'一个模拟HTTP响应的调试库'},
    {name:'dyci-main',        owner:'DyCI',              desc:'一个可以在调试时动态添加代码的工具 需要改动Xcode'},
    {name:'GestureLab',       owner:'markd2',            desc:'调试和把玩GestureRecognizor的'},
    {name:'cedar',            owner:'pivotal',           desc:'BDD风格单元测试'},
    {name:'iOS-UI-Assets',    owner:'pixelfreak',        desc:'iOS5.1中,系统控件和App的图片资源Dump 嗯..iOS7后就没用了'},
    {name:'iOS-Artwork-Extractor',    owner:'0xced',     desc:'导出iOS系统App及控件的图片资源 只支持到iOS5'}
    ]
},



{name:'旧代码 & 奇怪的东西',
list:[
    {name:'peertalk',            owner:'rsms',         desc:'一个苹果前员工开发的黑科技，通过USB在Mac和iOS之间高速的传递数据，被用于屏幕显示扩展'},
    {name:'DB5',                 owner:'quartermaster',desc:'通过plist构建界面的小东西'},
    {name:'HockeyKit',           owner:'TheRealKerni', desc:'一套iOS的 Ad-Hoc升级框架.包含PHP服务端'},
    {name:'Briefs',              owner:'capttaco',     desc:'一套类似原型制作工具'},
    {name:'OpenTLD',             owner:'zk00006',      desc:'视频跟踪检测 貌似挺高深'},
    {name:'SimFinger',           owner:'atebits',      desc:'一些Fake系统图标的App 还有一些设备外框的图片、触摸点图片可以用'},
    {name:'scifihifi-iphone',    owner:'ldandersen',   desc:'已经弃用的旧代码 新工程去看github页面'},
    {name:'iphonearkit',         owner:'zac',          desc:'4年前的代码 增强现实 (AR)'},
    {name:'TouchDB-iOS',         owner:'couchbaselabs',desc:'一个嵌入式的CouchDB实现'},
    {name:'iOS-Runtime-Headers', owner:'nst',          desc:'从运行时Dump出来的公有/私有 Framework头 通过这个可以进行不同版本的对比'},
    {name:'objectiveresource',   owner:'yfactorial',   desc:'RoR相关的东西 '},
    {name:'GRMustache',          owner:'groue',        desc:'Mustache模板?'},
    {name:'titanium_modules',    owner:'appcelerator', desc:'Titanium 的常用模块'},
    {name:'fontdiao',            owner:'lexrus',       desc:'类似FontAwesome的东西,包含了一些国内网站logo'}
    ]
},


{name:'代码库大包包',
list:[
    {name:'iphone-3.0-cookbook-',   owner:'erica',     desc:'随书代码'},
    {name:'iOS-5-Cookbook',         owner:'erica',     desc:'随书代码～'},
    {name:'iOS-6-Cookbook',         owner:'erica',     desc:''},
    {name:'iOS-6-Advanced-Cookbook',owner:'erica',     desc:''},
    {name:'Programming-iOS-Book-Examples',owner:'mattneub',desc:'Programming iOS 7 书代码'},
    {name:'iOS7-day-by-day',        owner:'ShinobiControls',desc:'iOS7-day-by-day 博客的代码'},
    {name:'iOS7-Sampler',           owner:'shu223',    desc:'iOS7的一些新功能演示~'},
    {name:'MyProjects',             owner:'chaozhao',  desc:'一些http:/ /mysparks.info上面的代码'},
    {name:'Xcode-Snippets',         owner:'mattt',     desc:'一些Xcode代码片段'}
    ]
},




{name:'Mac Only',
list:[
    {name:'gitx',              owner:'pieter',       desc:'一个git的图形客户端'},
    {name:'Chameleon',         owner:'BigZaphod',    desc:'把UIKit克隆到Mac里'},
    {name:'Induction',         owner:'Induction',    desc:'一个Mac上的数据库客户端 支持Mysql Postgre Nosql Redis等'},
    {name:'twui',              owner:'twitter',      desc:'一个Mac的自定义控件库,有类似iOS的Table和Tab,CA实现'},
    {name:'kod',               owner:'rsms',         desc:'Mac上的代码编辑,Chrome风格,小巧快速'},
    {name:'slate',             owner:'jigish',       desc:'Mac上窗口管理'},
    {name:'nu',                owner:'timburks',     desc:'一个包装,用nu语言来写东西？'},
    {name:'macgap',            owner:'maccman',      desc:'包装以可以用类似js的写法来调用函数'},
    {name:'Quicksilver',       owner:'quicksilver',  desc:'这个..Mac上知名的快速启动'},
    {name:'mogenerator',       owner:'rentzsch',     desc:'生成CoreData的Code'},
    {name:'nv',                owner:'scrod',        desc:'Note程序'},
    {name:'iTerm2',            owner:'gnachman',     desc:'知名终端～'},
    {name:'Sparkle',           owner:'andymatuschak',desc:'一个软件升级用的Framework'},
    {name:'PostgresApp',       owner:'PostgresApp',  desc:'PostgresSQL客户端'},
    {name:'terminal-notifier', owner:'alloy',        desc:'通过终端发送Notification'},
    {name:'ShiftIt',           owner:'fikovnik',     desc:'管理桌面窗口 状态栏插件'},
    {name:'textmate',          owner:'textmate',     desc:'这个不用说了。。～～～'},
    {name:'textmate-missingdrawer', owner:'jezdez',  desc:'Textmate插件 一个侧边栏'},
    {name:'AckMate',           owner:'protocool',    desc:'Textmate插件 运行ack？'},
    {name:'clicktoflash',      owner:'rentzsch',     desc:'Webkit插件 屏蔽Flash'},
    {name:'MongoHub-Mac',      owner:'bububa',       desc:'MongoDB的客户端'},
    {name:'CocosBuilder',      owner:'cocos2d',      desc:'用于cocos2d的JS绑定 GUI设计'},
    {name:'Rebel',             owner:'github',       desc:'一些AppKit的扩展'},
    {name:'Textual',           owner:'Codeux',       desc:'轻量的IRC客户端'},
    {name:'vico',              owner:'vicoapp',      desc:'一个开发用文本编辑器'},
    {name:'pomodoro',          owner:'ugol',         desc:'一个时间管理的App'},
    {name:'visor',             owner:'torsten',      desc:'Terminal的插件'},
    {name:'GoAgentX',          owner:'ohdarling',    desc:'这个不用说了....'},
    {name:'Pixen',             owner:'Pixen',        desc:'像素画 的工具'},
    {name:'Color-Picker-Pro',  owner:'oscardelben',  desc:'取色器 状态栏插件'},
    {name:'SNRHUDKit',         owner:'indragiek',    desc:'Mac版的HUD'},
    {name:'ConnectionKit',     owner:'karelia',      desc:'FTP和WebDAV'},
    {name:'OpenEmu',           owner:'OpenEmu',      desc:'各种游戏机模拟器'},
    {name:'mpv',               owner:'mpv-player',   desc:'视频播放器，定制功能强大，基于MPlayer'},
    {name:'Hacky',             owner:'eliaskg',      desc:'一个完整的Hacker News客户端～～'},
    {name:'WWDCDownloader',    owner:'zadr',         desc:'下载WWDC用，Xcode5 only'},
    {name:'QuickCast',         owner:'petetak',      desc:'一个录屏分享的App'},
    {name:'zephyros',          owner:'sdegutis',     desc:'窗口管理 for hackers'},
    {name:'shuttle',           owner:'fitztrev',     desc:'SSH快捷方式 菜单栏插件'},
    {name:'KeepingYouAwake',   owner:'newmarcel',    desc:'很小的工具栏插件，保持 Mac 不休眠'},
    {name:'WWDC',              owner:'insidegui',    desc:'在 Mac 上直接查看、下载 WWDC 视频和演讲稿'},
    {name:'qlstephen',         owner:'whomwah',      desc:'系统QuickLook的插件,查看无扩展名的文本文件'},
    {name:'INAppStoreWindow',  owner:'indragiek',    desc:'Mac AppStore风格的NSWindow'},
    {name:'spectacle',         owner:'eczarny',      desc:'窗口管理 不用鼠标'},
    {name:'limechat',          owner:'psychs',       desc:'IRC客户端'},
    {name:'LiveReload',        owner:'livereload',   desc:'前端开发,编辑代码后自动刷新,非常流行的App，已上架AppStore'},
    {name:'selfcontrol',       owner:'slambert',     desc:'自控。。禁止上网一段时间'},
    {name:'Popup',             owner:'shpakovski',   desc:'在状态栏弹出的Popup'},
    {name:'MPlayerX',          owner:'niltsh',       desc:'一个MPlayerX的测试分支'},
    {name:'QuickCursor',       owner:'QuickCursor',  desc:'快速启动编辑'},
    {name:'launchrocket',      owner:'jimbojsb',     desc:'PrefPane, 管理 Homebrew-installed services'},
    {name:'Sonora',            owner:'sonoramac',    desc:'一个小巧的 挺棒的音乐播放器'},
    {name:'google-music-mac.git',owner:'kbhomes',    desc:'如题,Google Music客户端'},
    {name:'SafariOmnibar',     owner:'rs',           desc:'一个Sarari插件'},
    {name:'HexFiend',          owner:'ridiculousfish',desc:'16进制编辑器'},
    {name:'macdown',           owner:'uranusjr',     desc:'很棒的Markdown编辑器'},
    {name:'atom',              owner:'atom',         desc:'Github官方的 21世纪开源代码编辑器 :)'},
    {name:'Cakebrew',          owner:'brunophilipe', desc:'Homebrew图形管理~'},
    {name:'sequelpro',         owner:'sequelpro',    desc:'Sequel Pro 访问MySQL'},
    {name:'DrawKit',           owner:'DrawKit',      desc:'Mac里矢量绘图的库，功能丰富'},
    {name:'GIFs',              owner:'orta',         desc:'在网站搜索GIF图片，已上架AppStore'},
    {name:'iSparta',           owner:'iSparta',      desc:'APNG 和 WebP 格式的转换, 腾讯出的, 用于QQ手机表情'},
    {name:'MIDIApps',          owner:'krevis',       desc:'两个App，一个是Midi monitoring，一个是SysEx'}
    ]
},


{name:'Xcode插件/开发工具',
list:[
    {name:'Alcatraz',               owner:'mneorr',         desc:'Xcode插件 管理和发现插件～～'},
    {name:'Polychromatic',          owner:'kolinkrewinkel', desc:'Xcode插件 为不同的变量类型赋予不同的颜色～'},
    {name:'ClangFormat-Xcode',      owner:'travisjeffery',  desc:'Xcode插件 clang-format 代码格式化'},
    {name:'BBUncrustifyPlugin-Xcode',owner:'benoitsan',     desc:'Xcode插件 Uncrustify格式化'},
    {name:'HOStringSense-for-Xcode',owner:'holtwick',       desc:'Xcode插件 直接编辑转义字符串'},
    {name:'ZLGotoSandboxPlugin',    owner:'MakeZL',         desc:'Xcode插件 快速打开模拟器的Sandbox文件夹'},
    {name:'cocoapods-xcode-plugin', owner:'kattrali',       desc:'Xcode插件 cocoapod'},
    {name:'KFCocoaPodsPlugin',      owner:'ricobeck',       desc:'Xcode插件 cocoapod, 方便编辑Podfile，显示构建日志'},
    {name:'FuzzyAutocompletePlugin',owner:'chendo',         desc:'Xcode插件 更好的代码自动补全'},
    {name:'XCActionBar',            owner:'pdcgomes',       desc:'Xcode插件 工作流, "Alfred for Xcode"'},
    {name:'XcodeBoost',             owner:'fortinmike',     desc:'Xcode插件 代码操作，例如符号高亮、方法复制、正则匹配等'},
    {name:'Dash-Plugin-for-Xcode',  owner:'omz',            desc:'Xcode插件 用Dash替代默认Doc浏览器'},
    {name:'VVDocumenter-Xcode',     owner:'onevcat',        desc:'Xcode插件 写注释时自动提醒JavaDoc风格'},
    {name:'SCXcodeSwitchExpander',  owner:'stefanceriu',    desc:'Xcode插件 在写switch时，自动补全所有选项 (只支持NS_ENUM)'},
    {name:'ColorSense-for-Xcode',   owner:'omz',            desc:'Xcode插件 支持动态调整UIColor'},
    {name:'KSImageNamed-Xcode',     owner:'ksuther',        desc:'Xcode插件 支持显示工程里的UIImage'},
    {name:'Lin-Xcode5',             owner:'questbeat',      desc:'Xcode插件 显示NSLocalizedString的对应字符串'},
    {name:'XToDo',                  owner:'trawor',         desc:'Xcode插件 列出所有TODO FIXME等 性能差'},
    {name:'CodePilot',              owner:'macoscope',      desc:'Xcode插件 快速查找和定位代码'},
    {name:'XVim',                   owner:'JugglerShu',     desc:'Xcode插件 支持绑定VIM快捷键'},
    {name:'CATweaker',              owner:'keefo',          desc:'Xcode插件/独立App 编辑CAMediaTimingFunction动画曲线'},
    {name:'tween-o-matic',          owner:'simonwhitaker',  desc:'编辑CAMediaTimingFunction动画曲线'},
    {name:'nib2objc',               owner:'akosma',         desc:'把xib和nib翻译成m 包括命令、GUI、Service'},
    {name:'iOS-Universal-Framework',owner:'kstenerud',      desc:'编译iOS的Framework的通用模板 支持armv7s'},
    {name:'iOS-Framework',          owner:'jverkoey',       desc:'编译iOS的Framework的通用模板'},
    {name:'Xcode5-Plugin-Template', owner:'kattrali',       desc:'Xcode5插件的开发模板'},
    {name:'Xcode4-Plugin-Template', owner:'kattrali',       desc:'Xcode4插件的开发模板'},
    {name:'XcodeEditor',            owner:'appsquickly',    desc:'解析和操作Xcode工程文件'},
    {name:'UIEffectDesignerView',   owner:'icanzilb',       desc:'原生iOS/Mac粒子效果设计'},
    {name:'SCStringsUtility',       owner:'stefanceriu',    desc:'国际化/翻译工具，用于制作和修改 localizable String'},
    {name:'avocado',                owner:'ideo',           desc:'非常强大的iOS交互设计工具箱,基于Facebook Origami'},
    {name:'JSONExport',             owner:'Ahmed-Ali',      desc:'贴上JSON字符串，生成ObjC/Swift/Java对象'},
    {name:'acani',                  owner:'Ahmed-Ali',      desc:'能通过 JSON 字符串直接生成 Object 代码'},
    {name:'appledoc',               owner:'tomaz',          desc:'通过代码注释生成doc文档,只支持ObjC'},
    {name:'jazzy',                  owner:'realm',          desc:'通过代码注释生成doc文档,支持ObjC/Swift,分析准确'},
    {name:'CocoaPods',              owner:'CocoaPods',      desc:'管理Cocoa库依赖'},
    {name:'Carthage',               owner:'Carthage',       desc:'去中心化的依赖管理 (类似cocoapods)'},
    {name:'APNS-Pusher',            owner:'blommegard',     desc:'通过APNS发推送～'}
    ]
},





{name:'Swift',
list:[

{name:'基础功能',
list:[
    {name:'ExSwift',            owner:'pNre',           desc:'一套 Extensions'},
    {name:'SwiftMoment',        owner:'akosma',         desc:'一个好用的时间处理的库 (Moment.js)'},
    {name:'Timepiece',          owner:'naoty',          desc:'一个时间处理的库 (NSDate)'},
    {name:'Design-Patterns-In-Swift',owner:'ochococo',  desc:'Swift设计模式展示'},
    {name:'HanekeSwift',        owner:'Haneke',         desc:'一个通用缓存'},
    {name:'SugarRecord',        owner:'SugarRecord',    desc:'数据存储的封装，支持CoreData/Realm'},
    {name:'SQLite.swift',       owner:'stephencelis',   desc:'SQLite封装'},
    {name:'Async',              owner:'duemunk',        desc:'GCD封装'},
    {name:'SwiftSSL',           owner:'SwiftP2P',       desc:'加密解密,支持MD5,SHA,HMac'},
    {name:'CryptoSwift',        owner:'krzyzanowskim',  desc:'加密解密,支持MD5,SHA,HMac,AES等'},
    {name:'Bond',               owner:'SwiftBond',      desc:'各种事件绑定'},
    {name:'Dollar.swift',       owner:'ankurp',         desc:'容器类的操作 (Underscore.js)'},
    {name:'Swiftz',             owner:'typelift',       desc:'函数式编程,重载了一坨运算符...'},
    {name:'Runes',              owner:'thoughtbot',     desc:'几个貌似有用的运算符重载 (如尼字母啊哈哈...)'},
    {name:'Euler',              owner:'mattt',          desc:'一些数学符号的运算符重载'}
    ]
},

{name:'框架',
list:[
    {name:'ReactKit',  owner:'ReactKit',            desc:'Reactive 框架'},
    {name:'RxSwift',   owner:'jspahrsummers',       desc:'ReactiveCocoa 的 Swift 试验性版本'},
    {name:'PromiseKit',owner:'mxcl',                desc:'Future and promise 方式编程. 这是一个双语版本的库(ObjC/Swift)'},
    {name:'SwiftTask', owner:'ReactKit',            desc:'任务管理 Promise + progress + pause + cancel + retry'},
    {name:'Cartography',owner:'robb',               desc:'Autolayout的封装'},
    {name:'SnapKit',    owner:'SnapKit',            desc:'Autolayout的封装'},
    {name:'C4iOS',      owner:'C4Framework',        desc:'一系列工具和扩展'}
    ]
},

{name:'网络',
list:[
    {name:'Alamofire',          owner:'Alamofire',      desc:'Swift最流行的HTTP请求库'},
    {name:'Just',               owner:'JustHTTP',       desc:'简单好用的HTTP请求库'},
    {name:'SwiftHTTP',          owner:'daltoniam',      desc:'简单的HTTP请求，简单包装自NSURLSession'},
    {name:'Moya',               owner:'Moya',           desc:'网络层封装，基于 Alamofire'},
    {name:'Starscream',         owner:'daltoniam',      desc:'WebSocket连接库'},
    {name:'Argo',               owner:'thoughtbot',     desc:'JSON解析与对象映射'},
    {name:'SwiftyJSON',         owner:'SwiftyJSON',     desc:'JSON解析'},
    {name:'ObjectMapper',       owner:'Hearst-DD',      desc:'JSON对象映射/相互转换'},
    {name:'KFSwiftImageLoader', owner:'kiavashfaisali', desc:'网络图片加载 (支持 iOS 和  Watch)'},
    {name:'Kingfisher',         owner:'onevcat',        desc:'网络图片加载 (仿SDWebImage)'}
    ]
},

{name:'动画',
list:[
    {name:'DKChainableAnimationKit',    owner:'Draveness',  desc:'通过链式代码让动画实现得更轻松'},
    {name:'Spring',                     owner:'MengTo',     desc:'很不错的动画库'}
    ]
},

{name:'控件/UI',
list:[
    {name:'PKHUD',              owner:'pkluz',       desc:'一个iOS8风格的HUD,效果不错'},
    {name:'TouchVisualizer',    owner:'morizotter',  desc:'一行代码,就可以把触摸位置显示到屏幕上'},
    {name:'Fingertips',         owner:'mapbox',      desc:'自定义UIWindow,可以把触摸位置显示到屏幕上'},
    {name:'KYCircularProgress', owner:'kentya6',     desc:'简单好用的环形进度条'},
    {name:'Persei',             owner:'Yalantis',    desc:'ScrollView顶部嵌入菜单,有不错的动画效果'},
    {name:'MarkdownTextView',   owner:'indragiek',   desc:'基于 TextKit 的 Markdown 文本框'},
    {name:'RichEditorView',     owner:'cjwirth',     desc:'富文本编辑、支持与HTML互相转换 (基于WebView)'},
    {name:'DynamicBlurView',    owner:'KyoheiG3',    desc:'毛玻璃效果，支持动画'},
    {name:'PullToMakeSoup',     owner:'Yalantis',    desc:'一个很有趣的下拉刷新动画'},
    {name:'BreakOutToRefresh',  owner:'dasdom',      desc:'下拉刷新动画里打砖头'},
    {name:'ParticleLab',        owner:'FlexMonkey',  desc:'用Metal实现的粒子系统'},
    {name:'MaterialKit',        owner:'nghialv',     desc:'一套有 Android Material 风格的控件 (涟漪动画)'},
    {name:'paper-switch',       owner:'Ramotion',    desc:'一个开关,有圆圈放大的动画 (Material 风格)'},
    {name:'ZFRippleButton',     owner:'zoonooz',     desc:'一套 Material 风格的 Button (涟漪动画)'},
    {name:'BubbleTransition',   owner:'andreamazz',  desc:'一个导航Transition，Material 风格的圆圈放大'},
    {name:'SevenSwitch',        owner:'bvogelzang',  desc:'几个自定义样式的Switch'},
    {name:'TextFieldEffects',   owner:'raulriera',   desc:'几个还不错的 TextField 效果'},
    {name:'PageMenu',           owner:'uacaps',      desc:'类似网易新闻那样的 Top Tabbar Controller'},
    {name:'WobbleView',         owner:'inFullMobile',desc:'左滑删除时，边缘抖动动画'},
    {name:'hamburger-button',   owner:'robb',        desc:'删除按钮与汉堡按钮之间的变化动画'},
    {name:'LTMorphingLabel',    owner:'lexrus',      desc:'UILabel特效 (实现了Keynote中不少特效) 很棒'},
    {name:'animated-tab-bar',   owner:'Ramotion',    desc:'Tabbar上的动画，支持翻转、弹簧、帧动画等'},
    {name:'adaptive-tab-bar',   owner:'Ramotion',    desc:'随着时间的流逝，自动隐藏文字保留图标的Tabbar...'},
    {name:'SAHistoryNavigationViewController',owner:'szk-atmosphere',desc:'导航栏返回时，以类似iOS多任务的界面展示所有历史内容，效果不错'},
    {name:'SCLAlertView-Swift', owner:'vikmeup',     desc:'一个自定义AlertView'},
    {name:'GuillotineMenu',     owner:'Yalantis',    desc:'一个在导航栏翻上翻下的菜单'},
    {name:'ios-charts',         owner:'danielgindi', desc:'图表绘制库,支持折线/饼图/柱状图/扇形/雷达图/K线等'},
    {name:'PNChart-Swift',      owner:'kevinzhow',   desc:'图表绘制库, PNChart的Swift版本'},
    {name:'XLActionController', owner:'xmartlabs',   desc:'各种样式的 action sheet, 使用简单'}
    ]
},

{name:'其他',
list:[
    {name:'CleanroomLogger',    owner:'emaloney',       desc:'Log工具, Swift版的CocoaLumberjack/log4j'},
    {name:'Quick',              owner:'Quick',          desc:'BDD测试框架, 支持ObjC'},
    {name:'Sleipnir',           owner:'railsware',      desc:'又一个BDD'},
    {name:'DBPathRecognizer',   owner:'didierbrun',     desc:'复杂的手势识别'},
    {name:'FontBlaster',        owner:'ArtSabintsev',   desc:'更方便的加载自定义字体'},
    {name:'Surge',              owner:'mattt',          desc:'Accelerate库的包装'},
    {name:'SwiftyBeaver',       owner:'SwiftyBeaver',   desc:'log工具，支持自定义颜色'},
    {name:'Toucan',             owner:'gavinbunney',    desc:'图片调整库，支持裁剪、调整大小、Mask、圆角等功能'},
    {name:'Siren',              owner:'ArtSabintsev',   desc:'升级时的提示弹框, (Harpy的Swift版本) 使用时需要谨慎对待AppStore审核'},
    {name:'MusicKit',           owner:'benzguo',        desc:'音乐分析、和弦探测、MIDI I/O'},
    {name:'Laurine',            owner:'JiriTrecak',     desc:'做国际化时，相关代码生成'}
    ]
},

{name:'App',
list:[
    {name:'Chats',         owner:'acani',             desc:'一个具有原生界面风格的聊天App (注意这个还有配套的开源服务端)'},
    {name:'SwiftWeather',  owner:'JakeLin',           desc:'一个不错的天气App'},
    {name:'focus',         owner:'mozilla',           desc:'Safari 内容屏蔽插件 App，Mozilla 出品，已上架'},
    {name:'VPNOn',         owner:'lexrus',            desc:'VPN连接管理,支持 Watch,已上架'},
    {name:'V2EXClient',    owner:'liaojinxing',       desc:'一个 V2EX 的一个客户端'},
    {name:'imWildCat',     owner:'imWildCat',         desc:'又一个 V2EX 客户端'},
    {name:'SwiftHN',       owner:'Dimillian',         desc:'一个 Hacker News 客户端'},
    {name:'News-YC---iPhone',   owner:'bennyguitar',  desc:'又一个 Hacker News 客户端'},
    {name:'FlappySwift',   owner:'fullstackio',       desc:'Flappy Bird'},
    {name:'swift-2048',    owner:'austinzheng',       desc:'2048'},
    {name:'eidolon',       owner:'artsy',             desc:'artsy.net 艺术品拍卖信息'}
    ]
}

]
},




{name:'非Github',
list:[
    {name:'cooliris-toolkit', url:'https://code.google.com/p/cooliris-toolkit/',  owner:'google', 
        desc:'Cooliris出品基础工具包,Github有Clone'},
    {name:'core-plot', url:'https://code.google.com/p/core-plot/',  owner:'google', 
        desc:'强大的2D数据绘图库'},
    {name:'j2objc', url:'https://code.google.com/p/j2objc/',  owner:'google', 
        desc:'神奇的东西,将Java翻译成ObjC～ Google出品'},
    {name:'theunarchiver', url:'https://code.google.com/p/theunarchiver/',  owner:'google', 
        desc:'解压,支持Zip, Tar, Gzip, Bzip2, 7-Zip, Rar, LhA, StuffIt等'},
    {name:'macfuse', url:'https://code.google.com/p/macfuse/',  owner:'google', 
        desc:'创建OSX的文件系统～'},
    {name:'google-toolbox-for-mac', url:'https://code.google.com/p/google-toolbox-for-mac/',  owner:'google', 
        desc:'著名的Google工具箱'},
    {name:'leveldb', url:'https://code.google.com/p/leveldb/',  owner:'google', 
        desc:'Google大神开发的KV存储,高性能,低内存'},
    {name:'RegexKitLite',url:'http://regexkit.sourceforge.net/RegexKitLite/',owner:'sf',
        desc:'著名的ObjC 正则表达式'},
    {name:'zipachive',  url:'https://code.google.com/p/ziparchive/',   owner:'google',
        desc:'用得很广泛的ObjC zip文件压缩解压 (github上有几个mirror)'}
    ]
}

];
